-- scripts/generate_users.py より生成
INSERT INTO users (name, display_name, description, password) VALUES ('鈴木 陽一', 'kaorisuzuki', '普段エステティシャンをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.takahashi.jp/\nメールアドレス: xinoue@yahoo.com\n', '9!5AgcWmQ@');
INSERT INTO users (name, display_name, description, password) VALUES ('山本 拓真', 'ryosuke75', '普段経営者をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.yamaguchi.jp/\nメールアドレス: vwatanabe@yahoo.com\n', 'gIfYB5Oqm+');
INSERT INTO users (name, display_name, description, password) VALUES ('山下 陽子', 'fujiwaraakira', '普段検察官をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.ikeda.jp/\nメールアドレス: ryoheiokamoto@hotmail.com\n', ')3AaHkiCa7');
INSERT INTO users (name, display_name, description, password) VALUES ('藤井 京助', 'kenichi46', '普段漫画家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://sato.com/\nメールアドレス: satoshota@yahoo.com\n', 'ujO08RwS_6');
INSERT INTO users (name, display_name, description, password) VALUES ('井上 淳', 'miurayasuhiro', '普段運転士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.ishii.jp/\nメールアドレス: kumikowatanabe@hotmail.com\n', '8_HZfg1s$C');
INSERT INTO users (name, display_name, description, password) VALUES ('遠藤 淳', 'ikedakazuya', '普段音響技術者をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://saito.net/\nメールアドレス: maayamatsumoto@gmail.com\n', '8k4Xx)9wg^');
INSERT INTO users (name, display_name, description, password) VALUES ('田中 学', 'nakamuranaoto', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://matsumoto.com/\nメールアドレス: mikitakahashi@hotmail.com\n', '33DEv!_#_p');
INSERT INTO users (name, display_name, description, password) VALUES ('三浦 翔太', 'miki08', '普段お笑い芸人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://suzuki.org/\nメールアドレス: taichi05@yahoo.com\n', '0*opW%Kp!j');
INSERT INTO users (name, display_name, description, password) VALUES ('佐藤 くみ子', 'yosuke79', '普段小説家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.ishii.jp/\nメールアドレス: yuki63@yahoo.com\n', '%86BURTp69');
INSERT INTO users (name, display_name, description, password) VALUES ('池田 京助', 'watanabesotaro', '普段寿司職人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://suzuki.jp/\nメールアドレス: takumakondo@hotmail.com\n', 'cJ&2Ow*gnk');
