INSERT INTO users (id, name, display_name, description, password) VALUES (1, 'vabe', '坂本 聡太郎', '普段医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://ogawa.jp/\nメールアドレス: takuma43@hotmail.com\n', '$2a$10$gjaotHZoumKefYz8oUlqCefwbx4IrsUzZ10RDyIWFGtbGkWAHV0xi');
INSERT INTO themes (user_id, dark_mode) VALUES (1, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (2, 'mmatsumoto', '清水 直人', '普段配管工をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.yamamoto.com/\nメールアドレス: shotaikeda@hotmail.com\n', '$2a$10$lqLqAQHiIHYMkIREWFGJUeTDQHPsvyOYV.O/bltC137DJ.HjQ25we');
INSERT INTO themes (user_id, dark_mode) VALUES (2, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (3, 'shoheihashimoto', '山下 太一', '普段ウェディングプランナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://sato.jp/\nメールアドレス: dsato@yahoo.com\n', '$2a$10$TyLaDfioqHiEvmIfnK9LnOuIxyiSG4zE4q5cwQW3arjpUrKnuRBvm');
INSERT INTO themes (user_id, dark_mode) VALUES (3, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (4, 'uhayashi', '岡本 陽一', '普段ウェディングプランナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.yamaguchi.net/\nメールアドレス: jun04@gmail.com\n', '$2a$10$zwGxkLE5WYeQrikiYxgk5etg8CU0.BKBmput4XuG6.r7Q7nkBFzFy');
INSERT INTO themes (user_id, dark_mode) VALUES (4, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (5, 'yosukekato', '井上 美加子', '普段花火師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://suzuki.net/\nメールアドレス: dtakahashi@yahoo.com\n', '$2a$10$2XhabwzviUjs0HjvnsVsDOp/d9ajhxeXChk/BqXhTTY.43EI15zJy');
INSERT INTO themes (user_id, dark_mode) VALUES (5, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (6, 'qsaito', '高橋 洋介', '普段グラフィックデザイナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.fujiwara.org/\nメールアドレス: itoryosuke@gmail.com\n', '$2a$10$ljdf6sPQB1WLi00etu9nau7/ePqJPVOGKIBn/xHEEuvCgjaKR0XFW');
INSERT INTO themes (user_id, dark_mode) VALUES (6, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (7, 'akemiwatanabe', '伊藤 和也', '普段医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://watanabe.com/\nメールアドレス: ryosuke25@yahoo.com\n', '$2a$10$ihinBGEg8LUfFs2GXfJT8Op2k2j4fN8MrThVeTsa5KXRiAapVIPSG');
INSERT INTO themes (user_id, dark_mode) VALUES (7, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (8, 'pwatanabe', '鈴木 知実', '普段アートディレクターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.goto.com/\nメールアドレス: lmatsumoto@hotmail.com\n', '$2a$10$Tn7UUWbJazRTVBffn.xrxuViXcNgWgzc.G62sWafw8FFf4KtcsGsG');
INSERT INTO themes (user_id, dark_mode) VALUES (8, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (9, 'maaya46', '山本 陽子', '普段医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://nakagawa.net/\nメールアドレス: saitominoru@yahoo.com\n', '$2a$10$PDoDxFbal/THC.JLuJDAXebpwdY1laJ5FDNX7OisYei3XEvEGIEWO');
INSERT INTO themes (user_id, dark_mode) VALUES (9, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (10, 'akemisato', '山田 晃', '普段栄養士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.nishimura.jp/\nメールアドレス: akira14@gmail.com\n', '$2a$10$xmpR3FmhuzT6gLGnLvY25ey7fGeFbi0royNW6Bq6OLn3MLy.84RAq');
INSERT INTO themes (user_id, dark_mode) VALUES (10, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (11, 'rgoto', '池田 涼平', '普段YouTuberをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://takahashi.org/\nメールアドレス: ikedamai@gmail.com\n', '$2a$10$PVGej/JNk6T5CCKIkR1QkOJgZ/ysOem218fE1zcvAdRgXkmX1EJ8m');
INSERT INTO themes (user_id, dark_mode) VALUES (11, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (12, 'satomiyamaguchi', '森 英樹', '普段アイドルをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://kobayashi.jp/\nメールアドレス: yumikonakagawa@yahoo.com\n', '$2a$10$fOmB7HAll0DVwNHdcHRDYOIF796ItZaPoarpLQZ7wuCEJOUrKHYGu');
INSERT INTO themes (user_id, dark_mode) VALUES (12, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (13, 'ryosuketakahashi', '石井 美加子', '普段大学教授をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.abe.jp/\nメールアドレス: znakamura@hotmail.com\n', '$2a$10$X7M2fYcEmAoEtwNgvWcL1uGusQ18b1T4Y3yjOkqSAGVAFfZCU1.Ky');
INSERT INTO themes (user_id, dark_mode) VALUES (13, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (14, 'yumikomurakami', '山田 千代', '普段脚本家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.sasaki.com/\nメールアドレス: rikafujita@yahoo.com\n', '$2a$10$I6ihAqeGHrYh1tlizNcLq.SyUZJ.2NB7XpRjVzcjJo1BzGzE2oalS');
INSERT INTO themes (user_id, dark_mode) VALUES (14, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (15, 'maaya18', '伊藤 知実', '普段歯科医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.okada.com/\nメールアドレス: oito@yahoo.com\n', '$2a$10$UG09WLt0k80UKUDtYbkbo.VhYgLBtA4jGzpGG3RPB4SIXBtWvfNdq');
INSERT INTO themes (user_id, dark_mode) VALUES (15, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (16, 'eogawa', '池田 直樹', '普段農家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.hayashi.com/\nメールアドレス: nakamurashota@gmail.com\n', '$2a$10$pVnVhN91b6Xurg06C3f7zORYs16TNKMijB8lDeHsp1HgQoMssTh4m');
INSERT INTO themes (user_id, dark_mode) VALUES (16, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (17, 'syamashita', '高橋 あすか', '普段花火師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.yamamoto.jp/\nメールアドレス: mikitanaka@gmail.com\n', '$2a$10$i4rGLRqBs4J.ZO5EKnEDJOBCTOmeiHyZz8RcX9KWpbG06OqJBaHwq');
INSERT INTO themes (user_id, dark_mode) VALUES (17, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (18, 'osato', '後藤 結衣', '普段演歌歌手をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.kondo.com/\nメールアドレス: rnakamura@gmail.com\n', '$2a$10$n4UzUYaXnnTOQsMDMaBfke5kJCFKpufvgZB2TgSdo07HSQJFlCKm6');
INSERT INTO themes (user_id, dark_mode) VALUES (18, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (19, 'qyamazaki', '山田 明美', '普段建築家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://yamaguchi.net/\nメールアドレス: satorei@yahoo.com\n', '$2a$10$U0CQpFEeJQ4GbUURM.LQo.SJzWx3ykVgVma4p9AAVN2xQO4STBDLa');
INSERT INTO themes (user_id, dark_mode) VALUES (19, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (20, 'ryoheiyamazaki', '伊藤 里佳', '普段和紙職人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.matsumoto.jp/\nメールアドレス: rei89@gmail.com\n', '$2a$10$.9o9APBSmIgPBdCGsyWFUOtei8u8KipTiOf8D4SoiL0vvwDyTUnGm');
INSERT INTO themes (user_id, dark_mode) VALUES (20, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (21, 'ogawaatsushi', '高橋 里佳', '普段お笑い芸人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.ito.com/\nメールアドレス: yoko11@gmail.com\n', '$2a$10$FCqdrBfQZuVe.HKN6q448eJF8uPlfzSE83LHC8Rz9bAc388mPJZcu');
INSERT INTO themes (user_id, dark_mode) VALUES (21, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (22, 'xnakamura', '森 翼', '普段公認会計士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.sasaki.org/\nメールアドレス: fukudanaoko@hotmail.com\n', '$2a$10$f8G8NBZWyoSmTzXBZylbvOgY1LMKtMGuL6jhO4zoy81QV9FB5tgd6');
INSERT INTO themes (user_id, dark_mode) VALUES (22, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (23, 'naokiishii', '長谷川 里佳', '普段配管工をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://inoue.org/\nメールアドレス: takahashihideki@gmail.com\n', '$2a$10$o25anRQnmnMbgi9z3Fs3ruCwLiSL9P4ytksMiU9KCPGcZVZ/AkGjm');
INSERT INTO themes (user_id, dark_mode) VALUES (23, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (24, 'miturufujiwara', '木村 京助', '普段アナウンサーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://abe.jp/\nメールアドレス: jkato@yahoo.com\n', '$2a$10$f91JS4d9zkFs58Em7wQFg.IfJRRhzfn/g.fX8AQLEmP2dpurDDP6.');
INSERT INTO themes (user_id, dark_mode) VALUES (24, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (25, 'yumikowatanabe', '鈴木 治', '普段脚本家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.nakajima.org/\nメールアドレス: myoshida@yahoo.com\n', '$2a$10$pT41458JnuCwWNrCRtUO2.UJ2wtdzXRsBarquucxEZRbdO.4eN3vS');
INSERT INTO themes (user_id, dark_mode) VALUES (25, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (26, 'shota21', '小林 篤司', '普段調理師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://inoue.jp/\nメールアドレス: sotarofujiwara@yahoo.com\n', '$2a$10$yhDh4MvuqJHFLTY0f1jXVOUCEBQUIMC9FlcMFcqWW4gn0NIFF7Rui');
INSERT INTO themes (user_id, dark_mode) VALUES (26, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (27, 'ewatanabe', '伊藤 舞', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.maeda.jp/\nメールアドレス: tmatsumoto@gmail.com\n', '$2a$10$gdJlG2.i5MbNxkYLGGxn3e7mm5vhBHTVZdqMKIhNbAHdoKJ8Ub5IW');
INSERT INTO themes (user_id, dark_mode) VALUES (27, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (28, 'yyamashita', '鈴木 舞', '普段営業をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.suzuki.com/\nメールアドレス: rika44@gmail.com\n', '$2a$10$Y68ncfdPmZ6lLvw4HoolXeNbdM2071SZuNYXuvTgRqehvJBLcn3Mq');
INSERT INTO themes (user_id, dark_mode) VALUES (28, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (29, 'shohei55', '高橋 舞', '普段薬剤師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.kato.org/\nメールアドレス: jyamamoto@yahoo.com\n', '$2a$10$RG/V1jBRKaOHDJwW.s6cSujNEeq2/58vWSzt5bcBIZ3oK9gBGnDwS');
INSERT INTO themes (user_id, dark_mode) VALUES (29, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (30, 'yumikoyoshida', '山口 修平', '普段医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://kato.jp/\nメールアドレス: maedaakira@yahoo.com\n', '$2a$10$iBU4vxtQTg4d.NAStK1MH.Oymg6pBIfXg0F8wcqZL/pXDXrydydkG');
INSERT INTO themes (user_id, dark_mode) VALUES (30, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (31, 'gkato', '吉田 あすか', '普段運転士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.nakamura.jp/\nメールアドレス: shohei39@hotmail.com\n', '$2a$10$2lp.9qdFiefFLBlbHKkrqefbftVgW2R5bSt0yi6Jqm6BTg8BlwvDG');
INSERT INTO themes (user_id, dark_mode) VALUES (31, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (32, 'asuka85', '松本 里佳', '普段電気工事士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.nakamura.jp/\nメールアドレス: pogawa@hotmail.com\n', '$2a$10$SNu1lK2q1ddYmE9piGAAD.r1sntx1nA1N8Gi9EO7nYixFoB53idDW');
INSERT INTO themes (user_id, dark_mode) VALUES (32, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (33, 'dmurakami', '吉田 舞', '普段占い師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.yoshida.com/\nメールアドレス: manabu58@gmail.com\n', '$2a$10$wBkAIoiijPyRU/VYf5CGw.TedsG0ZDqBp6eWto6kp0CDcJzt4xBA2');
INSERT INTO themes (user_id, dark_mode) VALUES (33, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (34, 'asuka70', '佐藤 篤司', '普段モデルをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.suzuki.jp/\nメールアドレス: imurakami@hotmail.com\n', '$2a$10$dJQX6Y9TFYr/clYlGc7KL.HWmaf/25Gv90FXwvOf3C/2mBu6f.2CW');
INSERT INTO themes (user_id, dark_mode) VALUES (34, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (35, 'fujiihanako', '後藤 康弘', '普段エステティシャンをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://kobayashi.org/\nメールアドレス: jinoue@yahoo.com\n', '$2a$10$i/9mdUfLmSpZEF1Qr3HsyeZkFzj2w8LR.F2CvogztSk1DGOecI8Oq');
INSERT INTO themes (user_id, dark_mode) VALUES (35, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (36, 'yumiko93', '鈴木 和也', '普段和紙職人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.yamamoto.com/\nメールアドレス: inouehiroshi@gmail.com\n', '$2a$10$8kBSlcJvfxAdkp15FJPPuOeKR4KIVUsQS60sbd.mNcmN89thNABVm');
INSERT INTO themes (user_id, dark_mode) VALUES (36, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (37, 'ryamashita', '佐藤 治', '普段医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://yoshida.jp/\nメールアドレス: aokiyumiko@gmail.com\n', '$2a$10$sAsWQ0Uc/Yz8PxA2QGif/uQiS3r8TDArtuwW0tz.KmPGIxfZLRLv6');
INSERT INTO themes (user_id, dark_mode) VALUES (37, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (38, 'haruka88', '村上 あすか', '普段電気工事士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://mori.org/\nメールアドレス: qkobayashi@hotmail.com\n', '$2a$10$hDkN1JXb3JONDJ/xRvmVzuY0pv6YsYBPJdnuGS8xSpzCqUeUfO1vC');
INSERT INTO themes (user_id, dark_mode) VALUES (38, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (39, 'yutasato', '佐藤 七夏', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.yamazaki.com/\nメールアドレス: paoki@yahoo.com\n', '$2a$10$fER61B1tmQ8nCOF/5g8z9eP4HJBu.pjdgZhqj11tmdJVy4lkmQzyi');
INSERT INTO themes (user_id, dark_mode) VALUES (39, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (40, 'bkimura', '佐藤 花子', '普段占い師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.murakami.jp/\nメールアドレス: takahashikaori@gmail.com\n', '$2a$10$JK43I4xnygLgyrtuotZ2u.XZ3sFDEmJoxY.eTqDDXj9NYRQur/DNm');
INSERT INTO themes (user_id, dark_mode) VALUES (40, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (41, 'shoheifujita', '橋本 香織', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://ikeda.jp/\nメールアドレス: maikimura@hotmail.com\n', '$2a$10$xIsZWWGEEZUpy7zW0LvEJegtdWs3f1UukEDviB1UerIF3ffDczZIa');
INSERT INTO themes (user_id, dark_mode) VALUES (41, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (42, 'umatsumoto', '高橋 幹', '普段イラストレーターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.nakamura.com/\nメールアドレス: dfujiwara@hotmail.com\n', '$2a$10$IwsKq1Z3jBi7/m739ReoWe77UR8TvEG/VCoVk7.ZJE5HS/SGZ1GIe');
INSERT INTO themes (user_id, dark_mode) VALUES (42, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (43, 'kenichi81', '佐藤 充', '普段気象予報士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://yamashita.net/\nメールアドレス: sakamotokazuya@gmail.com\n', '$2a$10$we52LKLUxtwof.bdGVbnyeM92zaxkOYNqxn2gIFD85hoadgMrZnbO');
INSERT INTO themes (user_id, dark_mode) VALUES (43, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (44, 'shoheiogawa', '小林 充', '普段営業をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://shimizu.org/\nメールアドレス: ogawaharuka@gmail.com\n', '$2a$10$FkAcqDUHwIoDIRsuEXVON.Az6IwN/uBbl8a/CBSyF8uY1.ENk3I5K');
INSERT INTO themes (user_id, dark_mode) VALUES (44, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (45, 'yasuhiro13', '加藤 治', '普段ウェディングプランナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://okada.com/\nメールアドレス: naokoabe@hotmail.com\n', '$2a$10$i0M1gA6hSsD1wc8CGrae3uWmmwb9wAV3qjMRJadw9gqyeEjUxopEq');
INSERT INTO themes (user_id, dark_mode) VALUES (45, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (46, 'ookada', '井上 太一', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.tanaka.org/\nメールアドレス: minoru96@gmail.com\n', '$2a$10$8rwGwLa6l4V.VXYVsM9FDuJqPPGTqTTgbKZIS4ltH4dGKd7a7qIru');
INSERT INTO themes (user_id, dark_mode) VALUES (46, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (47, 'taichishimizu', '斉藤 零', '普段大学教授をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://hasegawa.com/\nメールアドレス: abeyumiko@yahoo.com\n', '$2a$10$mjutEV91hAlmEB0tqi03V.xBHFNWKU.eCAeUADrTdV6muq/Oq6uXy');
INSERT INTO themes (user_id, dark_mode) VALUES (47, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (48, 'msato', '藤原 亮介', '普段ウェディングプランナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.matsuda.com/\nメールアドレス: gito@gmail.com\n', '$2a$10$s5zN4IkB1WrI28Gjf1Q7Vuex3gPpUu6CvC5kgNJWMPBVYZJtZbKLy');
INSERT INTO themes (user_id, dark_mode) VALUES (48, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (49, 'fukudaosamu', '高橋 陽子', '普段検察官をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://saito.com/\nメールアドレス: itokana@gmail.com\n', '$2a$10$t5K310LasESOU1N4b1BpqOpRJW8oX8Pi4mwgWkPZnylz5zCpqQq9G');
INSERT INTO themes (user_id, dark_mode) VALUES (49, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (50, 'tanakamaaya', '清水 洋介', '普段救急救命士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.sato.com/\nメールアドレス: minorukobayashi@gmail.com\n', '$2a$10$qXDd80VLLuoRt4MufCGzGOV3Six.jNAvSrlura0GJVRdyEv5EeV/e');
INSERT INTO themes (user_id, dark_mode) VALUES (50, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (51, 'kyosukenakamura', '前田 零', '普段建築家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.ikeda.com/\nメールアドレス: hiroshi39@gmail.com\n', '$2a$10$kIUTF2NKYDELpqItNyUQAOQgiZS4ILpUSP7QcFFkKfS8y.YlEW4V6');
INSERT INTO themes (user_id, dark_mode) VALUES (51, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (52, 'manabu56', '近藤 舞', '普段航海士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://ikeda.net/\nメールアドレス: momokoogawa@hotmail.com\n', '$2a$10$FiyB09ggT/MctT7rVFNzfeWz54stAU.AB53PU186UbvjhhsFoudBW');
INSERT INTO themes (user_id, dark_mode) VALUES (52, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (53, 'miturusato', '佐々木 陽子', '普段気象予報士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.tanaka.org/\nメールアドレス: hokamoto@gmail.com\n', '$2a$10$xSMauwAGkC368qeSc.UmfOL1m6ye4KPi7xcW0uDekhIylKW9GTQP6');
INSERT INTO themes (user_id, dark_mode) VALUES (53, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (54, 'asukahasegawa', '佐藤 裕樹', '普段漫画家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.yamamoto.com/\nメールアドレス: mikako12@yahoo.com\n', '$2a$10$2PRH3pYMlozvYXP5774f8OmlIEqtNBTGbRE12tFeTfvL5pdH7i2zS');
INSERT INTO themes (user_id, dark_mode) VALUES (54, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (55, 'yamamotoatsushi', '高橋 太郎', '普段アーティストをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://ito.jp/\nメールアドレス: mituru79@yahoo.com\n', '$2a$10$aMY6pSdUc7UYvn/nSW0PHefr2O/hbFROliFZI2Iqgw5DfOdekf15y');
INSERT INTO themes (user_id, dark_mode) VALUES (55, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (56, 'nishimurayoko', '高橋 里佳', '普段医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.sato.org/\nメールアドレス: mikakonakamura@yahoo.com\n', '$2a$10$Dqk5aiJkf3K/AdSbsgKfU.kA2ICwxzyk88FG1Ki77nKl51HBRRt8a');
INSERT INTO themes (user_id, dark_mode) VALUES (56, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (57, 'nanamiwatanabe', '小川 さゆり', '普段検察官をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://suzuki.org/\nメールアドレス: mikitanaka@yahoo.com\n', '$2a$10$K0psmr6Wh7Pn2p5OOLWEG.oX61.2QMhNu0iiSRY.BZ.Nhtd2apivO');
INSERT INTO themes (user_id, dark_mode) VALUES (57, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (58, 'rikawatanabe', '中村 太郎', '普段小説家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.sato.jp/\nメールアドレス: katonaoko@gmail.com\n', '$2a$10$49jVEPoyhyRyYuiy2LkjNOnspWuznUd/somH5InlbPay/Cx8n9eWm');
INSERT INTO themes (user_id, dark_mode) VALUES (58, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (59, 'sishikawa', '佐藤 幹', '普段高等学校教員をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://sato.jp/\nメールアドレス: kanakobayashi@hotmail.com\n', '$2a$10$oCoDWivX7DQ5bFbz/rB8UeVtl4LLcoDjU08Cr29HDGH/ROx2JOpFe');
INSERT INTO themes (user_id, dark_mode) VALUES (59, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (60, 'itakahashi', '山下 裕太', '普段グラフィックデザイナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://suzuki.com/\nメールアドレス: fsato@yahoo.com\n', '$2a$10$wVlv7OSHqJjK1V8G.Q8wm.Khcsn710IJgIOQq4XxF1P5XfeoYm0im');
INSERT INTO themes (user_id, dark_mode) VALUES (60, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (61, 'suzukimituru', '遠藤 花子', '普段高等学校教員をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.yamazaki.com/\nメールアドレス: suzukimomoko@gmail.com\n', '$2a$10$4KzLpRoSbgjnDJajU.royeV9FIX6Th07L8jKY.UDkvpJPmbSektri');
INSERT INTO themes (user_id, dark_mode) VALUES (61, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (62, 'kobayashitsubasa', '加藤 裕太', '普段作曲家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://hashimoto.com/\nメールアドレス: fukudaminoru@yahoo.com\n', '$2a$10$OOu5hMNSUompXtXa34eqKeZnFeIZcXyByXF8.6QdQ5xbUX1wQHIrG');
INSERT INTO themes (user_id, dark_mode) VALUES (62, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (63, 'wsakamoto', '佐藤 加奈', '普段コピーライターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.suzuki.jp/\nメールアドレス: chiyo14@gmail.com\n', '$2a$10$l6LIPpYsOH3MEeef62Mcd.eSkKQGyk7ha3NXmEjwybHjGA21uWLYW');
INSERT INTO themes (user_id, dark_mode) VALUES (63, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (64, 'katoyosuke', '田中 花子', '普段ゲームクリエイターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://ito.com/\nメールアドレス: suzukiatsushi@gmail.com\n', '$2a$10$xf6/qgIj4YkNHJiOwe6FtemxIh/Xy/4HnhrKzsXgNOG7VQoqwls/6');
INSERT INTO themes (user_id, dark_mode) VALUES (64, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (65, 'kondotomoya', '中島 康弘', '普段配管工をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://miura.jp/\nメールアドレス: manabu77@yahoo.com\n', '$2a$10$OwjPOnokDZoxZWoMJm83Su2JeCcOzc/SYN7uUXSmIoPcgjYWB9aEm');
INSERT INTO themes (user_id, dark_mode) VALUES (65, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (66, 'wsaito', '遠藤 太郎', '普段小説家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.mori.jp/\nメールアドレス: kobayashiyuta@yahoo.com\n', '$2a$10$cyhZdUt.ks8JX6f1IKCf8uXsSXSliSA6zSVX91F638hZjR3xwz0YW');
INSERT INTO themes (user_id, dark_mode) VALUES (66, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (67, 'mikako39', '山下 太一', '普段裁判官をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.kobayashi.jp/\nメールアドレス: haruka30@gmail.com\n', '$2a$10$dwfFDQOt0ZAyprhbXu/CCOAJPOdM09VY/hIgS29zEM2pBCO6ZYpae');
INSERT INTO themes (user_id, dark_mode) VALUES (67, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (68, 'kenichitanaka', '中村 康弘', '普段コピーライターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.sato.jp/\nメールアドレス: taichi12@gmail.com\n', '$2a$10$B5AbwLSGVi8ACCYePhtvwOiHWSmbpeUcmnblykU.iGfHraYPBPbvW');
INSERT INTO themes (user_id, dark_mode) VALUES (68, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (69, 'yosuke82', '林 学', '普段演歌歌手をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.nakajima.jp/\nメールアドレス: kobayashihiroshi@hotmail.com\n', '$2a$10$kBDsTgFXJOWh6yoNAlZt6OsFSOqgwxO/kwqLUWbut2hVHgiEcUyIe');
INSERT INTO themes (user_id, dark_mode) VALUES (69, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (70, 'yosuke53', '伊藤 涼平', '普段検察官をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://kobayashi.jp/\nメールアドレス: morinaoki@yahoo.com\n', '$2a$10$JgmW2VpWmYh3Y1MSsoNYK.o6lBG4uo9OTmI76HE2qhqMloCyzJyEW');
INSERT INTO themes (user_id, dark_mode) VALUES (70, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (71, 'matsumotoharuka', '中村 結衣', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://fujii.jp/\nメールアドレス: abenanami@hotmail.com\n', '$2a$10$hzM/pHNCLlEB5cmBY/rk4u/IuA3ud3714zp3vAiWcmjovBX1PsWFy');
INSERT INTO themes (user_id, dark_mode) VALUES (71, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (72, 'miki53', '橋本 康弘', '普段気象予報士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://sato.jp/\nメールアドレス: kaori76@hotmail.com\n', '$2a$10$8db79EdFD/7Fsj0Rpc2T6e68h9tjQHN.v12Vy4BVvt/MU1EyRZROq');
INSERT INTO themes (user_id, dark_mode) VALUES (72, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (73, 'yamamotomomoko', '石川 修平', '普段YouTuberをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://sato.com/\nメールアドレス: satomi58@gmail.com\n', '$2a$10$xdO/hxMrnNslDi85zTvMo.7hkHZt9Cbx2qSouz4y7um/LUhxNgf2e');
INSERT INTO themes (user_id, dark_mode) VALUES (73, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (74, 'naotokobayashi', '近藤 京助', '普段建築家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.abe.org/\nメールアドレス: kumiko61@gmail.com\n', '$2a$10$FldtJJOY8y9GenY2AjUizuLqxBPlKviVjSiAf0KWG9zzNChuD8xxm');
INSERT INTO themes (user_id, dark_mode) VALUES (74, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (75, 'xmatsumoto', '山本 裕樹', '普段音響技術者をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.mori.net/\nメールアドレス: miki86@hotmail.com\n', '$2a$10$DJGtDHUyV8qyzKkyOVB9bOgN6guSy2JNHCTk956oL.XUqgmFiHUz2');
INSERT INTO themes (user_id, dark_mode) VALUES (75, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (76, 'osamu86', '池田 陽一', '普段グラフィックデザイナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://nakagawa.jp/\nメールアドレス: hanakokobayashi@gmail.com\n', '$2a$10$3vaD2w3NbE3G1lmPhQ/V5e3mbflj7WVlfhMBCElc5d6RIFH6UbEbO');
INSERT INTO themes (user_id, dark_mode) VALUES (76, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (77, 'kaorifujiwara', '遠藤 裕美子', '普段司法書士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://ishii.com/\nメールアドレス: watanabemanabu@hotmail.com\n', '$2a$10$5c.DSlirIzOqFcyYjmE42.Rg6BVIh/qv3Kb0UevAsFGtXr986oI9e');
INSERT INTO themes (user_id, dark_mode) VALUES (77, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (78, 'tomoyayamada', '佐藤 直樹', '普段気象予報士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.yamaguchi.com/\nメールアドレス: knakajima@hotmail.com\n', '$2a$10$j8OELyLq3bM7i.k0JNQ3AO8ga6sXZn08TwPM1.N7sbsdxvdSZ6YlG');
INSERT INTO themes (user_id, dark_mode) VALUES (78, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (79, 'shohei77', '鈴木 幹', '普段エンジニア演奏家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://yamamoto.com/\nメールアドレス: hyamaguchi@hotmail.com\n', '$2a$10$PU9j0uj.YF3r3/O77VBWfu3klTfLM29uazXigX4L4N8uxvAIsTTsG');
INSERT INTO themes (user_id, dark_mode) VALUES (79, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (80, 'kimurayasuhiro', '坂本 和也', '普段測量士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://shimizu.jp/\nメールアドレス: maimurakami@gmail.com\n', '$2a$10$fZaIwhe6/i/nAVfjMRkGju7cBLBGkhQuMuuNvYKV2G4wCejSBgDte');
INSERT INTO themes (user_id, dark_mode) VALUES (80, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (81, 'matsumotonaoko', '田中 篤司', '普段映画監督をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://ito.com/\nメールアドレス: sotaro49@gmail.com\n', '$2a$10$46MQmNWQqbjrhBY0cojiH.rE6VzrSject0T/wi93gBPRcHE3Rc7hq');
INSERT INTO themes (user_id, dark_mode) VALUES (81, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (82, 'xmiura', '高橋 淳', '普段和紙職人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.nakajima.org/\nメールアドレス: kaori44@gmail.com\n', '$2a$10$5/sVSqHLq0n/uVrXHzveSelj6Ibkr4KfJT9VhqK1ekW6P/t48D0aW');
INSERT INTO themes (user_id, dark_mode) VALUES (82, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (83, 'atsushi93', '鈴木 亮介', '普段アートディレクターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://yamamoto.net/\nメールアドレス: nanami05@gmail.com\n', '$2a$10$2PME/EzNNg46CBuAKULeLuvllmX9.k490bfuJ.kwS.4DLXSm.jFKC');
INSERT INTO themes (user_id, dark_mode) VALUES (83, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (84, 'pkato', '渡辺 太一', '普段司法書士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://abe.com/\nメールアドレス: ngoto@hotmail.com\n', '$2a$10$To0yPabYydufDgkrhOPfX.jOUJR7zHhN8ZM8DG9xZnaDDwsPi1.Mu');
INSERT INTO themes (user_id, dark_mode) VALUES (84, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (85, 'sotaro89', '山下 涼平', '普段音楽家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.kobayashi.com/\nメールアドレス: hanako89@hotmail.com\n', '$2a$10$cF52a819m.UyVzhFJtgqgOtaZ0kMxgqRFKYC9qX6WPnNSM9mwtFva');
INSERT INTO themes (user_id, dark_mode) VALUES (85, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (86, 'yamadataichi', '井上 直樹', '普段栄養士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://sato.com/\nメールアドレス: yui56@hotmail.com\n', '$2a$10$vw9DluQOYtVR/1qGWcNEBu7xsEm8TWjSstLRDUc3wOt6H3QdY9l.q');
INSERT INTO themes (user_id, dark_mode) VALUES (86, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (87, 'itonanami', '鈴木 香織', '普段アニメーターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://miura.com/\nメールアドレス: nakamurakyosuke@hotmail.com\n', '$2a$10$GvQtDC0gBNjxUoe/vrPRbOWjJZLuWjXR9J1P/zZd5GNfbnF0uS2cS');
INSERT INTO themes (user_id, dark_mode) VALUES (87, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (88, 'matsudamikako', '坂本 翔太', '普段YouTuberをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://yamada.com/\nメールアドレス: yokotanaka@gmail.com\n', '$2a$10$iq7x2S7XilCjlsj2slDmieTSmmhNGyieEQfVrNr3x1H2Dx2im9vHK');
INSERT INTO themes (user_id, dark_mode) VALUES (88, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (89, 'moririka', '遠藤 美加子', '普段アナウンサーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://suzuki.com/\nメールアドレス: lnakajima@yahoo.com\n', '$2a$10$rvIZZoPpL42P.PikqA98Y.RUznbvIGC5gVvUDRQfIiF/b7IxIHyTW');
INSERT INTO themes (user_id, dark_mode) VALUES (89, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (90, 'yamaguchimiki', '木村 淳', '普段バスガイドをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.takahashi.com/\nメールアドレス: morimaaya@yahoo.com\n', '$2a$10$6kkfQuc4ulsQqbRuW4bDzupCDYLenlS09GeU/s53WpHqy73v3k1b.');
INSERT INTO themes (user_id, dark_mode) VALUES (90, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (91, 'yoichimori', '伊藤 里佳', '普段ウェディングプランナーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://kobayashi.org/\nメールアドレス: rei09@hotmail.com\n', '$2a$10$r62r1OnYRYXT1SeygeyGPOWSlj9KWgpM3LmdetZTZH7K8P3TNLSFi');
INSERT INTO themes (user_id, dark_mode) VALUES (91, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (92, 'yamamotoyuki', '中村 英樹', '普段介護ヘルパーをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://fujita.jp/\nメールアドレス: yumikohashimoto@yahoo.com\n', '$2a$10$b7z10rWKPkg/ga.b652fxuj1cSKxQ0p6VeTVcv4NnZ1dPO11yvLNy');
INSERT INTO themes (user_id, dark_mode) VALUES (92, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (93, 'naoki52', '吉田 くみ子', '普段寿司職人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://www.maeda.net/\nメールアドレス: naoto97@gmail.com\n', '$2a$10$SbS/6V7T2ch6BuWxZF29Juzpf72.vPNEOny2ni5rfI.7x1g1YqaUy');
INSERT INTO themes (user_id, dark_mode) VALUES (93, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (94, 'hanakosuzuki', '山田 浩', '普段エンジニア演奏家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://kondo.jp/\nメールアドレス: hiroshiikeda@hotmail.com\n', '$2a$10$X6HMzuRe/QURXjluyd41Tup4yHFcbUf9FK3AnsAWF57iks3z4xDeC');
INSERT INTO themes (user_id, dark_mode) VALUES (94, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (95, 'naoki74', '伊藤 春香', '普段小説家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://tanaka.jp/\nメールアドレス: hideki58@hotmail.com\n', '$2a$10$nuOx3nFQQtG5nxAo9kJIWeORojL7gcHDS6KWqdN6w34ivzVw1cKua');
INSERT INTO themes (user_id, dark_mode) VALUES (95, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (96, 'okamotoyui', '藤田 陽一', '普段漫画家をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://tanaka.net/\nメールアドレス: gsato@hotmail.com\n', '$2a$10$T294VCeUIyXrBDNGqeDZceAhZ6LLbo7nHCJBbueahwESfo7FWN9aC');
INSERT INTO themes (user_id, dark_mode) VALUES (96, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (97, 'yoichinakagawa', '鈴木 治', '普段気象予報士をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.kimura.jp/\nメールアドレス: suzukisotaro@yahoo.com\n', '$2a$10$Rzsp8nDezrRADQIkMBFF5.dpeoG5kZwjHRFWjZGxW5ovuDEE6k.Zm');
INSERT INTO themes (user_id, dark_mode) VALUES (97, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (98, 'hanakosasaki', '中村 知実', '普段寿司職人をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: https://okada.jp/\nメールアドレス: myamada@yahoo.com\n', '$2a$10$gAI6Wcq7mKSXy3sFzk5afelzZCV9ezuDrJIfstOZp.P7oNBJGU8JO');
INSERT INTO themes (user_id, dark_mode) VALUES (98, true);
INSERT INTO users (id, name, display_name, description, password) VALUES (99, 'kanaabe', '池田 美加子', '普段ゲームクリエイターをしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://www.hayashi.jp/\nメールアドレス: moriyumiko@hotmail.com\n', '$2a$10$w6DufZf17XMnjSkpzOjsXug0HzgUSWsqfLdzyCDoWOAmIpjRhpKh6');
INSERT INTO themes (user_id, dark_mode) VALUES (99, false);
INSERT INTO users (id, name, display_name, description, password) VALUES (100, 'cnakajima', '渡辺 直子', '普段歯科医師をしています。\nよろしくおねがいします！\n\n連絡は以下からお願いします。\n\nウェブサイト: http://watanabe.jp/\nメールアドレス: ekimura@yahoo.com\n', '$2a$10$tiHELF/Ycc98w8DfXGrQneik73LuLQg6FvYCRu3hsVPHMxpS5m/6u');
INSERT INTO themes (user_id, dark_mode) VALUES (100, true);