DELETE FROM themes;
DELETE FROM icons;
DELETE FROM reservation_slots;
DELETE FROM livestream_tags;
DELETE FROM livestream_viewers_history;
DELETE FROM livecomment_reports;
DELETE FROM ng_words;
DELETE FROM reactions;
DELETE FROM tags;
DELETE FROM livecomments;
DELETE FROM livestreams;
DELETE FROM users;

ALTER TABLE `themes` auto_increment = 1;
ALTER TABLE `icons` auto_increment = 1;
ALTER TABLE `reservation_slots` auto_increment = 1;
ALTER TABLE `livestream_tags` auto_increment = 1;
ALTER TABLE `livestream_viewers_history` auto_increment = 1;
ALTER TABLE `livecomment_reports` auto_increment = 1;
ALTER TABLE `ng_words` auto_increment = 1;
ALTER TABLE `reactions` auto_increment = 1;
ALTER TABLE `tags` auto_increment = 1;
ALTER TABLE `livecomments` auto_increment = 1;
ALTER TABLE `livestreams` auto_increment = 1;
ALTER TABLE `users` auto_increment = 1;