// 
// Generated by @himenon/openapi-typescript-code-generator v0.27.1
// 
// OpenApi : 3.1.0
// 
// 


export namespace Schemas {
    export interface Theme {
        dark_mode: boolean;
    }
    export interface Tag {
        id: number;
        name: string;
        created_at: number;
    }
    export interface Reaction {
        id: number;
        emoji_name: string;
        user_id: number;
        livestream_id: number;
        created_at: number;
    }
    export interface User {
        /** Unique identifier for the given user. */
        id: number;
        name: string;
        display_name: string;
        description: string;
        created_at?: number;
    }
    export interface Livestream {
        id?: number;
        user_id?: number;
        title?: string;
        description?: string;
        start_at?: number;
        end_at?: number;
        created_at?: number;
        updated_at?: number;
    }
    export interface LivestreamView {
        id?: number;
        owner_id?: number;
        channel_id?: number;
        title?: string;
        description?: string;
        playlist_url?: string;
        start_at?: number;
        end_at?: number;
        created_at?: number;
        updated_at?: number;
    }
    /** 上位チャットの投稿 */
    export interface Superchat {
        id?: number;
        user_id?: number;
        livestream_id?: number;
        comment?: string;
        tip?: number;
        created_at?: number;
        updated_at?: number;
    }
    export interface LivesteamStatistics {
        total_viewers?: number;
        total_tips?: number;
        total_superchats?: number;
        total_reactions?: number;
        previous_livestream_total_viewers_diff?: number;
        previous_livestream_total_tips_diff?: number;
        previous_livestream_total_superchats_diff?: number;
        previous_livestream_total_reactions_diff?: number;
    }
    export interface UserStatistics {
        average_viewers?: number;
        average_tips?: number;
        average_superchats?: number;
        average_reactions?: number;
    }
    export interface SuperchatReport {
        id?: number;
        user_id?: number;
        superchat_id?: number;
        created_at?: number;
        updated_at?: number;
    }
}
export namespace Responses {
    /** Example response */
    export namespace GetTag {
        export interface Content {
            "application/json": Schemas.Tag[];
        }
    }
    /** Example response */
    export namespace GetUser {
        export interface Content {
            "application/json": Schemas.User;
        }
    }
    /** Example response */
    export namespace GetUserTheme {
        export interface Content {
            "application/json": Schemas.Theme;
        }
    }
    /** Example response */
    export namespace GetUserStatistics {
        export interface Content {
            "application/json": Schemas.UserStatistics;
        }
    }
    /** Example response */
    export namespace GetLivestreams {
        export interface Content {
            "application/json": Schemas.Livestream[];
        }
    }
    /** Example response */
    export namespace GetLivestream {
        export interface Content {
            "application/json": Schemas.LivestreamView;
        }
    }
    /** Example response */
    export namespace GetLivestreamStatistics {
        export interface Content {
            "application/json": Schemas.LivesteamStatistics;
        }
    }
    /** Example response */
    export namespace GetSuperchats {
        export interface Content {
            "application/json": Schemas.Superchat[];
        }
    }
}
export namespace RequestBodies {
    export namespace PostUser {
        export interface Content {
            "application/json": {
                name?: string;
                display_name?: string;
                description?: string;
                password?: string;
                theme?: Schemas.Theme;
            };
        }
    }
    export namespace Login {
        export interface Content {
            "application/json": {
                username?: string;
                password?: string;
            };
        }
    }
    export namespace PostReaction {
        export interface Content {
            "application/json": {
                emoji_name?: string;
            };
        }
    }
    export namespace PostSuperchat {
        export interface Content {
            "application/json": {
                comment?: string;
                tip?: number;
            };
        }
    }
    export namespace ReserveLivestream {
        export interface Content {
            "application/json": {
                title?: string;
                description?: string;
                start_at?: number;
                end_at?: number;
            };
        }
    }
}
