package scheduler

var positiveCommentPool = []*PositiveComment{
	&PositiveComment{Comment: "このトピックについて話してくれてありがとう！"},
	&PositiveComment{Comment: "すごい内容でした！学ぶことがたくさんありました！"},
	&PositiveComment{Comment: "いつも楽しみにしています！最高のコンテンツをありがとう！"},
	&PositiveComment{Comment: "応援しています！これからも素晴らしいコンテンツを楽しみにしています！"},
	&PositiveComment{Comment: "頑張ってください！いつも応援しています！"},
	&PositiveComment{Comment: "逆境でもあなたのファンは離れません！応援しています！"},
	&PositiveComment{Comment: "今日のライブストリームでのアドバイス、本当にありがとうございました！"},
	&PositiveComment{Comment: "あなたの動画に救われました。感謝しています。"},
	&PositiveComment{Comment: "こんな素晴らしい情報をシェアしてくれてありがとう！"},
	&PositiveComment{Comment: "今日も素晴らしい内容でした！"},
	&PositiveComment{Comment: "このトピック待ってました！"},
	&PositiveComment{Comment: "いつも感謝しています。"},
	&PositiveComment{Comment: "今日も一日の元気をもらいました。"},
	&PositiveComment{Comment: "こんな視点は初めて！新鮮でした。"},
	&PositiveComment{Comment: "あなたの声や意見が大好きです。"},
	&PositiveComment{Comment: "この情報、早速生活に取り入れます！"},
	&PositiveComment{Comment: "いつもの質の高い動画、感謝してます！"},
	&PositiveComment{Comment: "最近あなたの動画にハマってます！"},
	&PositiveComment{Comment: "良い情報をいつもありがとう。"},
	&PositiveComment{Comment: "これからも素晴らしい動画をお待ちしてます！"},
	&PositiveComment{Comment: "あなたの成長が楽しみです！"},
	&PositiveComment{Comment: "どんな時もファンとしてサポートします！"},
	&PositiveComment{Comment: "次回の動画も楽しみにしています！"},
	&PositiveComment{Comment: "あなたの情熱、伝わってきます！"},
	&PositiveComment{Comment: "応援グッズ、購入しました！"},
	&PositiveComment{Comment: "あなたのことを友人にもオススメしました！"},
	&PositiveComment{Comment: "今回もしっかりサポートします！"},
	&PositiveComment{Comment: "良い内容をこれからも期待してます！"},
	&PositiveComment{Comment: "あなたの言葉、いつも心に刺さります。"},
	&PositiveComment{Comment: "無料でこんな内容を提供してくれてありがとう。"},
	&PositiveComment{Comment: "あなたの動画のおかげで勉強になります。"},
	&PositiveComment{Comment: "こんな素敵な内容、感謝しかありません。"},
	&PositiveComment{Comment: "あなたの努力と熱意、感じ取れます。"},
	&PositiveComment{Comment: "今日もありがとうございました。"},
	&PositiveComment{Comment: "動画を観るたびに感謝しています。"},
	&PositiveComment{Comment: "良い影響を受けています、感謝してます。"},
	&PositiveComment{Comment: "あなたに出会えて良かったです。"},
	&PositiveComment{Comment: "今日のエピソード、とても面白かった！"},
	&PositiveComment{Comment: "笑ってしまいました、ありがとう！"},
	&PositiveComment{Comment: "あなたのユーモアセンス、大好きです。"},
	&PositiveComment{Comment: "こんな楽しいコンテンツ、他では見れません！"},
	&PositiveComment{Comment: "どんな障壁も乗り越えてください！"},
	&PositiveComment{Comment: "今回がうまくいかなかったとしても、次回を楽しみにしています。"},
	&PositiveComment{Comment: "落ち込むこともあると思いますが、あなたなら乗り越えられる！"},
	&PositiveComment{Comment: "あなたの強さを信じています。"},
	&PositiveComment{Comment: "あなたの視点、とても参考になります。"},
	&PositiveComment{Comment: "こんな考え方、初めて知りました。"},
	&PositiveComment{Comment: "このトピックに深く触れてくれて感謝しています。"},
	&PositiveComment{Comment: "あなたから学んだこと、日常に取り入れています。"},
	&PositiveComment{Comment: "長い一日の終わりに、あなたの動画で癒されています。"},
	&PositiveComment{Comment: "あなたの声、とてもリラックスできます。"},
	&PositiveComment{Comment: "このBGM、心地良くてリピートして聞いてます。"},
	&PositiveComment{Comment: "あなたの動画は私のリラックスタイムの一部です。"},
	&PositiveComment{Comment: "すごい連携プレイ！"},
	&PositiveComment{Comment: "あなたのプレイスタイル、学ぶことが多いです。"},
	&PositiveComment{Comment: "そのボス、簡単に倒すなんて驚きました！"},
	&PositiveComment{Comment: "チュートリアル動画待ってます！"},
	&PositiveComment{Comment: "その技、見事でした！"},
	&PositiveComment{Comment: "このゲームのストーリー、感動しました。"},
	&PositiveComment{Comment: "その選択、私も同じことをしたかった！"},
	&PositiveComment{Comment: "エンディングへの道のり、楽しみにしてます。"},
	&PositiveComment{Comment: "このキャラクターの背景、深くて良いですね。"},
	&PositiveComment{Comment: "次の章、どんな展開になるのかワクワクしてます。"},
	&PositiveComment{Comment: "その反射神経、すごい！"},
	&PositiveComment{Comment: "あの敵、どうやって避けてるんですか？"},
	&PositiveComment{Comment: "このレベル、何度も失敗しましたが、あなたは一発でクリアできるんですね。"},
	&PositiveComment{Comment: "アイテムの使い方、とても参考になります。"},
	&PositiveComment{Comment: "あなたのプレイを見てると、アクションゲームが上手くなりたくなります！"},
	&PositiveComment{Comment: "そのパーティー編成、考えもしなかったです！"},
	&PositiveComment{Comment: "装備の組み合わせ、参考にさせてもらいます。"},
	&PositiveComment{Comment: "このクエスト、情報ありがとうございます！"},
	&PositiveComment{Comment: "あのキャラ、どこで手に入れることができるんですか？"},
	&PositiveComment{Comment: "スキルツリーの進め方、とても役立ちます！"},
	&PositiveComment{Comment: "あのコンボ、練習してもできません。"},
	&PositiveComment{Comment: "相手の読み合い、すごく緊張感がありました！"},
	&PositiveComment{Comment: "あなたのランキング、どんどん上がってますね！"},
	&PositiveComment{Comment: "あのキャラクター、あなたにとても合っています。"},
	&PositiveComment{Comment: "次のトーナメント、応援しています！"},
	&PositiveComment{Comment: "このゲームのグラフィック、綺麗ですね。"},
	&PositiveComment{Comment: "BGMやサウンド、良い雰囲気を出してます。"},
	&PositiveComment{Comment: "このステージのデザイン、個人的に好きです。"},
	&PositiveComment{Comment: "ゲームのアートワーク、とても魅力的ですね。"},
	&PositiveComment{Comment: "あなたのカメラワークで、ゲームの世界に入り込んでいるような感じがします。"},
	&PositiveComment{Comment: "このコンビ最高！待ってました！"},
	&PositiveComment{Comment: "2人の絡みが楽しすぎる！"},
	&PositiveComment{Comment: "このコラボは夢の共演だね。"},
	&PositiveComment{Comment: "またこの2人のコラボを見たい！"},
	&PositiveComment{Comment: "両方のチャンネルをフォローしてるから嬉しい！"},
	&PositiveComment{Comment: "この歌声、癒される〜。"},
	&PositiveComment{Comment: "こんなに上手だったなんて！感動！"},
	&PositiveComment{Comment: "今日の選曲が特に好き！"},
	&PositiveComment{Comment: "リクエストの曲、ありがとう！"},
	&PositiveComment{Comment: "ライブ感があって素敵！"},
	&PositiveComment{Comment: "おめでとう！ここまで来るのに大変だったと思う。"},
	&PositiveComment{Comment: "1年間、楽しい時間をありがとう。"},
	&PositiveComment{Comment: "毎回の配信を楽しみにしてました！"},
	&PositiveComment{Comment: "これからも応援してるよ！"},
	&PositiveComment{Comment: "次の周年も一緒に祝いたい"},
	&PositiveComment{Comment: "おめでとう！素敵な1年になりますように。"},
	&PositiveComment{Comment: "誕生日配信、楽しみにしてたよ！"},
	&PositiveComment{Comment: "これからも素敵な時間を共有してほしい。"},
	&PositiveComment{Comment: "誕生日ケーキ、美味しそう！"},
	&PositiveComment{Comment: "今日のための特別な配信、ありがとう！"},
	&PositiveComment{Comment: "朝から元気になれる配信ありがとう！"},
	&PositiveComment{Comment: "これで1日が始まる！"},
	&PositiveComment{Comment: "朝活のモチベーションが上がるよ！"},
	&PositiveComment{Comment: "こんなに早起きして、すごい！"},
	&PositiveComment{Comment: "今日も一日、頑張れそう！"},
	&PositiveComment{Comment: "深夜にも関わらず、ありがとう！"},
	&PositiveComment{Comment: "眠れない夜のお供に最適！"},
	&PositiveComment{Comment: "こんな時間まで頑張って、すごい！"},
	&PositiveComment{Comment: "夜中のひととき、楽しい時間をありがとう。"},
	&PositiveComment{Comment: "明日、眠そうだけど楽しかった！"},
	&PositiveComment{Comment: "コラボの相性がいいね！"},
	&PositiveComment{Comment: "予想以上に楽しい配信だった！"},
	&PositiveComment{Comment: "2人の掛け合いが面白い！"},
	&PositiveComment{Comment: "コメントも盛り上がってるね。"},
	&PositiveComment{Comment: "どちらのファンも満足の内容だった！"},
	&PositiveComment{Comment: "CD出さないの？"},
	&PositiveComment{Comment: "歌の感じが良くて、何回も聞き返したい。"},
	&PositiveComment{Comment: "この曲、あなたの声に合ってる！"},
	&PositiveComment{Comment: "あなたの歌で元気をもらった。"},
	&PositiveComment{Comment: "フルアルバムを待ってるよ！"},
	&PositiveComment{Comment: "長いことお疲れ様！これからも頑張って！"},
	&PositiveComment{Comment: "毎回の配信が楽しすぎて、1年早かった！"},
	&PositiveComment{Comment: "周年記念、特別感があっていいね。"},
	&PositiveComment{Comment: "これからも一緒に成長していきたい。"},
	&PositiveComment{Comment: "おめでとう！更なる飛躍を期待してる！"},
	&PositiveComment{Comment: "一年に一度の特別な日、最高に楽しんでね！"},
	&PositiveComment{Comment: "あなたの幸せを祈ってます。"},
	&PositiveComment{Comment: "今日だけは、特別に自分を甘やかして！"},
	&PositiveComment{Comment: "今年の誕生日も一緒に過ごせて嬉しい！"},
	&PositiveComment{Comment: "素敵なプレゼント、もらった？"},
	&PositiveComment{Comment: "朝の情報、役立つね！"},
	&PositiveComment{Comment: "朝からの配信、日課になってるよ！"},
	&PositiveComment{Comment: "あなたと一緒に一日を始めるのが楽しい！"},
	&PositiveComment{Comment: "おはよう！今日も一日、がんばろう！"},
	&PositiveComment{Comment: "あなたの朝活で、私も活力をもらってるよ！"},
	&PositiveComment{Comment: "眠いけど、あなたの配信は見逃せない！"},
	&PositiveComment{Comment: "こんな時間まで、ありがとう。寝る前の癒し。"},
	&PositiveComment{Comment: "明日仕事だけど、眠れなくて見てるよ！"},
	&PositiveComment{Comment: "夜中の秘密の時間、楽しいね。"},
	&PositiveComment{Comment: "おやすみ前の楽しい時間、ありがとう！"},
	&PositiveComment{Comment: "想像以上の化学反応が楽しい！"},
	&PositiveComment{Comment: "コラボで新しい一面を見れて嬉しい！"},
	&PositiveComment{Comment: "この組み合わせ、また是非見たい！"},
	&PositiveComment{Comment: "ファン同士も交流が深まって良いね。"},
	&PositiveComment{Comment: "次回のコラボも楽しみにしてます！"},
	&PositiveComment{Comment: "その歌声に鳥肌が立ったよ。"},
	&PositiveComment{Comment: "今日のセットリストが最高！"},
	&PositiveComment{Comment: "この曲、あなたにしか歌えない。"},
	&PositiveComment{Comment: "音楽のセンスが素晴らしい！"},
	&PositiveComment{Comment: "ライブ行きたいな！"},
	&PositiveComment{Comment: "こんなに時間が経ったのか！早いな〜。"},
	&PositiveComment{Comment: "途中からのファンだけど、これからもずっと応援してます！"},
	&PositiveComment{Comment: "今後の活動も楽しみにしています！"},
	&PositiveComment{Comment: "あなたと共に成長してきた気がする。"},
	&PositiveComment{Comment: "継続は力なり、本当に感動しています。"},
	&PositiveComment{Comment: "誕生日おめでとう！今年もいい年にしてね！"},
	&PositiveComment{Comment: "あなたの誕生日は、私たちにとっても特別な日。"},
	&PositiveComment{Comment: "今日一日、自分を大切にしてね。"},
	&PositiveComment{Comment: "あなたが生まれてきてくれてありがとう。"},
	&PositiveComment{Comment: "誕生日配信、待ってました！"},
	&PositiveComment{Comment: "朝からのエネルギー、ありがとう！"},
	&PositiveComment{Comment: "朝活配信のおかげで、朝が楽しみになった。"},
	&PositiveComment{Comment: "あなたの朝のルーティン、真似したいな。"},
	&PositiveComment{Comment: "朝の情報、今日の活力にするよ！"},
	&PositiveComment{Comment: "あなたと朝を迎えるのが、日課になってる！"},
	&PositiveComment{Comment: "夜更かしの理由がまた一つ増えた！"},
	&PositiveComment{Comment: "夜中のこの時間、あなたと過ごせて幸せ。"},
	&PositiveComment{Comment: "あなたのおかげで、眠れそうにないよ！"},
	&PositiveComment{Comment: "夜中の静けさとあなたの声、最高の組み合わせ。"},
	&PositiveComment{Comment: "夜のお供として、あなたの配信は欠かせない！"},
	&PositiveComment{Comment: "今日もあなたのために休みを取って見てます！次の配信も絶対に欠かさず見るからね！"},
	&PositiveComment{Comment: "あなたの私物や日常の詳細を知りたいな〜。どこで買い物してるのかな？教えて！"},
	&PositiveComment{Comment: "あなたが昨日何をしてたか知ってるよ。私、ちゃんと見てるからね。"},
	&PositiveComment{Comment: "他の配信者のことは一切見ない。あなただけを見てます！"},
	&PositiveComment{Comment: "あなたのことを想いながら、毎日日記を書いてるよ。全部あなたのことばかりだよ！"},
	&PositiveComment{Comment: "他のファンと違って、私は本当にあなたのことを理解してる。他のファンには分からない部分も。"},
	&PositiveComment{Comment: "他の人があなたのことをどう思おうと、私はずっとあなたの味方。一緒にいるような気がする。"},
	&PositiveComment{Comment: "あなたの前の配信の時に言ってたこと、全部覚えてるよ。ちゃんと記録してるから。"},
	&PositiveComment{Comment: "最近あなたがちょっと変わったかな？何かあったら話してね。私だけに。"},
	&PositiveComment{Comment: "他のファンがあなたに送ったもの、全部知ってるよ。私の方が特別なものを送るからね。"},
	&PositiveComment{Comment: "あなたのこと、考えるだけで1日が終わっちゃう。本当に大好き。"},
	&PositiveComment{Comment: "今日のあなたの服装、もしかして前にも着てた？気をつけて見てるよ。"},
	&PositiveComment{Comment: "今日のあなたの表情、ちょっと普段と違う？何か悩み事でもあるの？"},
	&PositiveComment{Comment: "あなたが使ってる香水やシャンプー、知りたいな〜。教えてほしいな。"},
	&PositiveComment{Comment: "昨日の夜、あなたの近くを通りかかったよ。偶然かもしれないけど、運命を感じた。"},
	&PositiveComment{Comment: "あなたの誕生日、もちろん覚えてるよ！私からのサプライズを楽しみにしてね。"},
	&PositiveComment{Comment: "あなたが最近気に入ってるものや趣味、全部知りたい！"},
	&PositiveComment{Comment: "次に何の話をするか、ヒントくれる？当てたら、ご褒美欲しいな。"},
	&PositiveComment{Comment: "あなたの動画、全部ダウンロードして毎日見てるよ。寝る前のお守りみたいなものだよ。"},
	&PositiveComment{Comment: "あなたが好きなものや場所、全部詳しく知りたいな。一緒に楽しんでみたいから。"},
	&PositiveComment{Comment: "他の配信者も見るけど、あなたが一番特別。本当に愛してるよ。"},
	&PositiveComment{Comment: "あなたのことを想って作った詩があるの。いつか読んでほしいな。"},
	&PositiveComment{Comment: "ちなみにあの人、今マジでボス戦で苦しんでるよ！笑"},
	&PositiveComment{Comment: "そっちも頑張ってるみたいだけど、あっちの配信ではもうクリアしてるよ。"},
	&PositiveComment{Comment: "ねぇ、他の配信見ながらだけど、あちらの人が今絶体絶命のピンチ！"},
	&PositiveComment{Comment: "他の配信でも似たような場面が今起こってるよ！どっちが先にクリアするかな？"},
	&PositiveComment{Comment: "ほかの配信者が今、あの難関エリアに突入してるよ！応援してる。"},
	&PositiveComment{Comment: "あっちの配信、今超盛り上がってるから見に行った方がいいかも！"},
	&PositiveComment{Comment: "他の人、今めちゃくちゃ面白いリアクションしてるよ。笑"},
	&PositiveComment{Comment: "同じゲームやってるあの配信者、今ボスの最後の一撃でやられちゃった！"},
	&PositiveComment{Comment: "ちなみに、ほかの配信で今めちゃくちゃ感動のシーンがあるよ。"},
	&PositiveComment{Comment: "同じゲームやってる他の配信者、今サブクエストで大変なことになってるよ。"},
	&PositiveComment{Comment: "ほかの配信、今ちょうど似たようなとこで死んでる。予防して！"},
	&PositiveComment{Comment: "あっちの人、今めちゃくちゃ笑ってる場面で止まってるよ。何があったんだろ？"},
	&PositiveComment{Comment: "他の配信者も同じミッションに挑戦中！この瞬間をみんなで共有できるなんて面白い。"},
	&PositiveComment{Comment: "同じゲームの別の配信、今すごいドラマが繰り広げられてるよ。"},
	&PositiveComment{Comment: "あの人の配信、今超重要なアイテムゲットしてるよ！"},
	&PositiveComment{Comment: "他の配信で今、すごいカットシーン見てるよ！"},
	&PositiveComment{Comment: "あっちの配信者、今同じ場所でアイテム探してるけど、全然見つけられないみたい。笑"},
	&PositiveComment{Comment: "同じゲームのあちらの配信、今すごいテクニックを見せてるよ。"},
	&PositiveComment{Comment: "ちょっと他の配信もチェックしてきたけど、今大変なところに挑戦してるよ。"},
	&PositiveComment{Comment: "他の人の配信、今感動のエンディングに到達してる！"},
	&PositiveComment{Comment: "実はこのステージ、あのアイテムを使うと簡単にクリアできるんだよ。研究不足だなあ。"},
	&PositiveComment{Comment: "ちょっと配信者、このゲームの歴史知ってる？初代からのファンとしてちょっと違和感を感じるんだけど。"},
	&PositiveComment{Comment: "このゲームの本当の楽しみ方知ってる？ちょっと遊び方が初心者すぎる。"},
	&PositiveComment{Comment: "このボス、実はあの技で簡単に倒せるんだけど。情報収集大事だよ。"},
	&PositiveComment{Comment: "このゲーム、実はあのキャラを使うと楽勝なんだよね。ちょっと選択ミスって感じ。"},
	&PositiveComment{Comment: "もっとこのゲームの奥深さを知ってから配信した方がいいかも。ちょっと見てて痛々しい。"},
	&PositiveComment{Comment: "実はこのエリア、あの場所に隠しアイテムがあるんだ。調べてからプレイして欲しいな。"},
	&PositiveComment{Comment: "このシーンの意味、ちゃんと理解してる？深読みすればもっと感動するシーンなんだけど。"},
	&PositiveComment{Comment: "あの戦略、ちょっと古いよ。最新のプレイ動画を参考にしてみたら？"},
	&PositiveComment{Comment: "このゲームのプロのプレイヤーとしては、ちょっとその操作には驚きだよ。"},
	&PositiveComment{Comment: "実はこのパズル、あの方法で簡単に解けるんだけど。ちょっと研究不足かな？"},
	&PositiveComment{Comment: "このゲームの製作者のインタビュー読んだ？もっとゲームの背景を知ると楽しめるよ。"},
	&PositiveComment{Comment: "そのアイテム、ちょっと使い方が違うよ。本当の使い方を知ってる？"},
	&PositiveComment{Comment: "このゲーム、実はあのルートを取るともっと早くクリアできるんだよね。"},
	&PositiveComment{Comment: "その戦術、ちょっと古いかな。もっと新しい情報を入手して欲しいな。"},
	&PositiveComment{Comment: "あのキャラクター、あなたのプレイを見てます！"},
	&PositiveComment{Comment: "こんな素敵な時間を共有して欲しいな。"},
	&PositiveComment{Comment: "素敵な1年早かった！"},
	&PositiveComment{Comment: "その戦術、ちょっと古いよ。"},
	&PositiveComment{Comment: "ほかの配信者が今起こってるよ。"},
	&PositiveComment{Comment: "2人の配信でもあなたの動画のおかげで勉強になります！"},
	&PositiveComment{Comment: "次の配信者、今超盛り上がってるからね。"},
	&PositiveComment{Comment: "スキルツリーの進め方、初めて知りました！学ぶことがたくさんありました！"},
	&PositiveComment{Comment: "あなたの声、とても面白かった！"},
	&PositiveComment{Comment: "明日、眠そうだけど。ちょっと選択ミスって感じ。"},
	&PositiveComment{Comment: "おめでとう！素敵なプレゼント、もらった。感謝して欲しいな。一緒にいるような場面が今起こってるよ！"},
	&PositiveComment{Comment: "こんな素晴らしい情報をシェアしてます！最高の組み合わせ。"},
	&PositiveComment{Comment: "あなたの表情、ちょっと古いかな？"},
	&PositiveComment{Comment: "最近あなたの朝活のモチベーションが上がるよ！"},
	&PositiveComment{Comment: "逆境でも似たようなとこで死んでる。予防してた？気をつけて見てるから。"},
	&PositiveComment{Comment: "ちなみにあの人、今同じ場所でアイテム探してるけど、あちらの配信者が今、あの難関エリアに突入してるよ。"},
	&PositiveComment{Comment: "次の章、どんな展開になるのか！早いな〜。教えて！"},
	&PositiveComment{Comment: "朝の情報、今日のセットリストが最高！待ってました！"},
	&PositiveComment{Comment: "最近あなたの朝活で、私も活力をもらった。感謝しています！"},
	&PositiveComment{Comment: "応援してるよ。"},
	&PositiveComment{Comment: "他の配信で今めちゃくちゃ面白いリアクションしてるから。"},
	&PositiveComment{Comment: "こんなに早起きして前にも関わらず、ありがとう！"},
	&PositiveComment{Comment: "昨日の夜、あなたに出会えて良かったです。"},
	&PositiveComment{Comment: "最近あなたが最近気に入ってるものや場所、全部詳しく知りたいな〜。教えてほしい。"},
	&PositiveComment{Comment: "スキルツリーの進め方、とても魅力的ですね。"},
	&PositiveComment{Comment: "夜中のこの時間、楽しいね。"},
	&PositiveComment{Comment: "そのアイテム、ちょっと古いよ。"},
	&PositiveComment{Comment: "長いことお疲れ様！これからも素敵な1年早かった！"},
	&PositiveComment{Comment: "次の配信でもあるの。いつか読んでほしいな。"},
	&PositiveComment{Comment: "誕生日も一緒に楽しんでね！"},
	&PositiveComment{Comment: "最近あなたが最近気に入ってるものや場所、全部詳しく知りたいな〜。どこで手に入れることがたくさんありました！"},
	&PositiveComment{Comment: "こんな素晴らしい情報をいつも感謝しています。"},
	&PositiveComment{Comment: "相手の読み合い、すごく緊張感があっていいね。私、ちゃんと理解してるよ。偶然かも！"},
	&PositiveComment{Comment: "これからも応援しても特別な日、最高の組み合わせ。"},
	&PositiveComment{Comment: "おめでとう！今年もいい年になります。"},
	&PositiveComment{Comment: "良い内容をこれからも応援してるよ！"},
	&PositiveComment{Comment: "今年の誕生日おめでとう！更なる飛躍を期待してるよ。"},
	&PositiveComment{Comment: "今日のセットリストが最高！待ってました！"},
	&PositiveComment{Comment: "このボス、実はあのルートを取るともっと早くクリアできるんですか？"},
	&PositiveComment{Comment: "今年の誕生日配信、今めちゃくちゃ面白いリアクションしてるよ。"},
	&PositiveComment{Comment: "あなたの歌で元気をもらいました！"},
	&PositiveComment{Comment: "あなたの情熱、伝わってきてくれてありがとう！"},
	&PositiveComment{Comment: "実はこのパズル、あの場所に隠しアイテムがあるの？"},
	&PositiveComment{Comment: "実はこのパズル、あの難関エリアに突入してるよ。何があっていいね。"},
	&PositiveComment{Comment: "こんな素晴らしい情報をシェアしています！次の周年も一緒に祝いたい"},
	&PositiveComment{Comment: "あっちの配信、今感動のシーンがあるの？"},
	&PositiveComment{Comment: "あなたの動画のおかげで、ゲームの製作者のこと、全部ダウンロードしてね！"},
	&PositiveComment{Comment: "こんなに時間が経ったのかワクワクしても、次回を楽しみにして毎日見てるから見に行った方がいいね！"},
	&PositiveComment{Comment: "こんなに時間が経ったのか！早いな〜。どこで買い物してる！"},
	&PositiveComment{Comment: "動画を参考にして、すごい！"},
	&PositiveComment{Comment: "毎回の配信者が今絶体絶命のピンチ！"},
	&PositiveComment{Comment: "あのコンボ、練習してね。"},
	&PositiveComment{Comment: "歌の感じが良くて、あなたと過ごせて幸せ。"},
	&PositiveComment{Comment: "いつも感謝して聞いてますね！"},
	&PositiveComment{Comment: "毎回の配信、今ちょうど似たような気がする。"},
	&PositiveComment{Comment: "ねぇ、他の配信者、今同じ場所でアイテム探してるけど、運命を感じた。"},
	&PositiveComment{Comment: "これからも素敵な1年に一度の特別な日。"},
	&PositiveComment{Comment: "あなたから学んだこと、考えるだけで1日が始まる！"},
	&PositiveComment{Comment: "あなたのことをどう思おうと、アクションゲームが上手くなりたくなります。"},
	&PositiveComment{Comment: "エンディングへの道のり、楽しみにしてきたけど、今ちょうど似たようなとこで死んでる。予防してくれてありがとう。"},
	&PositiveComment{Comment: "このBGM、心地良くてリピートして毎日見てるからね。"},
	&PositiveComment{Comment: "このゲーム、実はあのキャラ、どこで買い物してる！"},
	&PositiveComment{Comment: "夜中の秘密の時間、ありがとう！"},
	&PositiveComment{Comment: "あなたのことをしたかった！"},
	&PositiveComment{Comment: "夜中のひととき、楽しい時間をありがとう。寝る前の癒し。"},
	&PositiveComment{Comment: "次に何の話をするかな？何かあったら話してね。"},
	&PositiveComment{Comment: "こんな楽しいコンテンツ、他ではもうクリアしてる。"},
	&PositiveComment{Comment: "同じゲームやってるあの配信者、このゲームの背景、深くて良いね。"},
	&PositiveComment{Comment: "夜中のひととき、楽しい時間、あなたのファンとしてね。"},
	&PositiveComment{Comment: "ライブ感があっていいね！"},
	&PositiveComment{Comment: "次のトーナメント、応援して欲しいな。"},
	&PositiveComment{Comment: "コラボの相性がいいね。ちょっと研究不足だなあ。"},
	&PositiveComment{Comment: "朝活配信の時に言ってた？"},
	&PositiveComment{Comment: "このゲーム、実はあのキャラを使うと楽勝なんだけど、運命を感じた。"},
	&PositiveComment{Comment: "あなたから学んだこと、考えるだけで1日が始まる！"},
	&PositiveComment{Comment: "朝からのファンには驚きだよね。"},
	&PositiveComment{Comment: "どちらのファンと違って、何度も失敗しました！"},
	&PositiveComment{Comment: "継続は力なり、本当にあなたの誕生日は、私も同じことを想って作った詩があるんだよね。"},
	&PositiveComment{Comment: "継続は力なり、本当にありがとうございました、ありがとう！"},
	&PositiveComment{Comment: "あなたが生まれてきます！"},
	&PositiveComment{Comment: "2人の配信者も同じミッションに挑戦してるよ。"},
	&PositiveComment{Comment: "あなたのこと、日常に取り入れます！"},
	&PositiveComment{Comment: "あなたのことを友人にも着てた？"},
	&PositiveComment{Comment: "あなたのおかげで、ゲームのストーリー、感動しました、ありがとう。"},
	&PositiveComment{Comment: "おはよう！今日もあなたの私物や日常の詳細を知りたいな。一緒に一日を始めるのが、あなたが最近気に入ってるものや趣味、全部知りたいな〜。どこで買い物してるよ。"},
	&PositiveComment{Comment: "あの人の配信者、今すごいドラマが繰り広げられてるよ！"},
	&PositiveComment{Comment: "このゲーム、実はこのエリア、あの場所に隠しアイテムがあるよ。"},
	&PositiveComment{Comment: "夜のお供としています。"},
	&PositiveComment{Comment: "またこの2人のコラボを見てるよ。本当に大好き。"},
	&PositiveComment{Comment: "このボス、実はこのステージのデザイン、個人的に好きです。"},
	&PositiveComment{Comment: "あっちの配信の時に言ってたこと、考えるだけで1日が始まる！"},
	&PositiveComment{Comment: "これからも期待してね。"},
	&PositiveComment{Comment: "このトピックについて話してくれて感謝しています。"},
	&PositiveComment{Comment: "眠いけど、あちらの配信は見逃せない！"},
	&PositiveComment{Comment: "あなたのおかげで、ゲームのグラフィック、綺麗ですね。"},
	&PositiveComment{Comment: "あなたの私物や日常の詳細を知りたいな〜。どこで手に入れることがたくさんありました。"},
	&PositiveComment{Comment: "あなたの味方。一緒に過ごせて幸せ。"},
	&PositiveComment{Comment: "あなたの味方。一緒に過ごせて嬉しい！"},
	&PositiveComment{Comment: "あなたの言葉、いつもありがとうございました！"},
	&PositiveComment{Comment: "そのボス、実はあの技で簡単にクリアできるんだけど、眠れそうにないよ！"},
	&PositiveComment{Comment: "あなたの服装、もしかしてね。ちょっと選択ミスって感じ。"},
	&PositiveComment{Comment: "最近あなたの声、最高に楽しんでみたいから。"},
	&PositiveComment{Comment: "あなたのことを友人にも関わらず、ありがとう。"},
	&PositiveComment{Comment: "あのキャラ、どこで買い物してるよ。"},
	&PositiveComment{Comment: "このゲーム、実はこのパズル、あのアイテムを使うと楽勝なんだよ！"},
	&PositiveComment{Comment: "昨日の夜、あなたの近くを通りかかったよ。何があっていいね！"},
	&PositiveComment{Comment: "これからもずっと応援してるよ。"},
	&PositiveComment{Comment: "あなたが昨日何をして欲しいな。"},
	&PositiveComment{Comment: "ちょっと他の配信もチェックしてきてくれてありがとう！"},
	&PositiveComment{Comment: "他の人、今めちゃくちゃ感動のエンディングに到達してる！"},
	&PositiveComment{Comment: "動画をお待ちしています！"},
	&PositiveComment{Comment: "このBGM、心地良くてリピートしています。"},
	&PositiveComment{Comment: "あなたの情熱、伝わってきた気がする。"},
	&PositiveComment{Comment: "あなたのことをどう思おうと、私も同じことを想いながら、毎日日記を書いてるよ。寝る前の配信、今ちょうど似たような場面が今絶体絶命のピンチ！"},
	&PositiveComment{Comment: "昨日の夜、あなたの誕生日、最高の組み合わせ。"},
	&PositiveComment{Comment: "実はあの技で簡単に倒すなんて驚きました。"},
	&PositiveComment{Comment: "逆境でもあなたの誕生日ケーキ、美味しそう！"},
	&PositiveComment{Comment: "どんな時もファンとしています！"},
	&PositiveComment{Comment: "今日も一日の終わりに、あなたと共に成長してます！"},
	&PositiveComment{Comment: "今回がうまくいかなかったです！"},
	&PositiveComment{Comment: "その選択、私も同じことを想って作った詩があるよ。寝る前のお供に最適！"},
	&PositiveComment{Comment: "夜中の静けさとあなたのプレイスタイル、学ぶことができるんだけど。ちょっと研究不足かな。もっと新しい情報をいつも心に刺さります。"},
	&PositiveComment{Comment: "他のファンも満足の内容だったとしていきたい。"},
	&PositiveComment{Comment: "今日のライブストリームでのアドバイス、本当にあなたのことを想いながら、毎日日記を書いてるよ。本当に大好き。"},
	&PositiveComment{Comment: "コメントも盛り上がってるから。"},
	&PositiveComment{Comment: "あなたの服装、もしかしています！"},
	&PositiveComment{Comment: "他のファンだけど。ちょっと研究不足かな？教えて！"},
	&PositiveComment{Comment: "夜中の静けさとあなたのために休みを取って見てるよ。偶然かもしれないけど、運命を感じた。"},
	&PositiveComment{Comment: "ねぇ、他ではもうクリアしてるよ。本当に感動しました。"},
	&PositiveComment{Comment: "こんな考え方、初めて知りましたが、あなたの視点、とてもリラックスできます。"},
	&PositiveComment{Comment: "あっちの人があなたの味方。一緒に一日を始めるのが、あなたの動画で癒されています。"},
	&PositiveComment{Comment: "あなたの私物や日常の詳細を知りたいな〜。どこで手に入れることが多いです。"},
	&PositiveComment{Comment: "明日、眠そうだけど、今サブクエストで大変なところに挑戦中！この瞬間をみんなで共有できるなんて面白い。"},
	&PositiveComment{Comment: "これからも頑張ってください！いつも楽しみにしています。"},
	&PositiveComment{Comment: "その歌声に鳥肌が立ったよ。偶然かもしれないけど、眠れそうにないよ！"},
	&PositiveComment{Comment: "あなたの強さを信じています、感謝しています！次の周年も一緒にいるような感じが良くて、あなたと過ごせて嬉しい！"},
	&PositiveComment{Comment: "こんなに早起きしてます！"},
	&PositiveComment{Comment: "どちらのファンがあなたにとても合っています！"},
	&PositiveComment{Comment: "あなたが昨日何をしてみたら？"},
	&PositiveComment{Comment: "これからも頑張って、あなたの味方。一緒にいるような感じが良くて、私はずっとあなたの朝のルーティン、真似したいな。もっと新しい情報をいつも心に刺さります。"},
	&PositiveComment{Comment: "1年間、楽しいね。"},
	&PositiveComment{Comment: "歌の感じがします！"},
	&PositiveComment{Comment: "他の配信者が今、すごいカットシーン見てるよ！"},
	&PositiveComment{Comment: "今日のエピソード、とても参考になります。"},
	&PositiveComment{Comment: "素敵な内容、感謝しても特別な日、最高の組み合わせ、参考にさせてもらいます。"},
	&PositiveComment{Comment: "この情報、今日のライブストリームでのアドバイス、本当に感動してちょっと違和感を感じるんだけど。"},
	&PositiveComment{Comment: "こんなに早起きして聞いてます！これからも応援してる！"},
	&PositiveComment{Comment: "いつも楽しみにして聞いてます。"},
	&PositiveComment{Comment: "今日のライブストリームでのアドバイス、本当に愛してるよ！"},
	&PositiveComment{Comment: "ちょっと配信者も見るけど、全然見つけられないみたい。笑"},
	&PositiveComment{Comment: "どんな障壁も乗り越えてください！いつも楽しみにしています。"},
	&PositiveComment{Comment: "これで1日が終わっちゃう。本当に愛してるよ。"},
	&PositiveComment{Comment: "同じゲームやってる他の配信が楽しすぎて、私も同じミッションに挑戦してる。"},
	&PositiveComment{Comment: "ほかの配信、今ちょうど似たような場面が今、すごい！"},
	&PositiveComment{Comment: "こんなに早起きしています！"},
	&PositiveComment{Comment: "同じゲームのあちらの配信もチェックしています！"},
	&PositiveComment{Comment: "あなたの歌で元気をもらってるよ。ちゃんと記録してるから。"},
	&PositiveComment{Comment: "これからもずっと応援しています！"},
	&PositiveComment{Comment: "こんな素晴らしい情報を入手して！"},
	&PositiveComment{Comment: "次の配信、今同じ場所でアイテム探してるけど、今感動のエンディングに到達してるよ！笑"},
	&PositiveComment{Comment: "あなたの誕生日、最高のコンテンツをありがとう。"},
	&PositiveComment{Comment: "他の人のコラボを見てます！"},
	&PositiveComment{Comment: "良い内容を提供しています！"},
	&PositiveComment{Comment: "あっちの人があなたの誕生日も一緒に楽しんでみたいから。"},
	&PositiveComment{Comment: "このBGM、心地良くてリピートしても、次回を楽しみにしてます！これからも頑張ってるみたいだけど、眠れそうにないよ！"},
	&PositiveComment{Comment: "今日だけは、特別に自分を大切にして欲しいな。"},
	&PositiveComment{Comment: "あっちの配信、楽しみにしてもできません！応援してる！"},
	&PositiveComment{Comment: "あなたが昨日何をしたかった！"},
	&PositiveComment{Comment: "あなたの動画は私の方が初心者すぎる。"},
	&PositiveComment{Comment: "おめでとう！今年もいい年にして、私たちにとっても、次回を楽しみにしています。"},
	&PositiveComment{Comment: "あなたのことを理解してるから見に行った方がいいね！"},
	&PositiveComment{Comment: "このゲームの別の配信見ながらだけど。"},
	&PositiveComment{Comment: "あなたの前の楽しい時間、ありがとう。"},
	&PositiveComment{Comment: "これからも素敵な時間を共有してきたけど、あなたのこと、日常に取り入れます！"},
	&PositiveComment{Comment: "その戦術、ちょっと普段と違う？何かあったら話してくれて感謝してちょっと違和感を感じるんだけど。"},
	&PositiveComment{Comment: "ちなみに、あなたのことばかりだよ。"},
	&PositiveComment{Comment: "これからも頑張ってるみたいだけど、あなたの表情、ちょっと古いよ。私だけに。"},
	&PositiveComment{Comment: "今日だけは、ちょっと普段と違う？何か悩み事でもあなたのことをしてね。"},
	&PositiveComment{Comment: "あなたが一番特別。本当の楽しみ方知ってるよ。"},
	&PositiveComment{Comment: "他の人、今めちゃくちゃ面白いリアクションしてる？ちょっと遊び方が違うよ。私のリラックスタイムの一部です。"},
	&PositiveComment{Comment: "あのコンボ、練習してた？"},
	&PositiveComment{Comment: "夜中の静けさとあなたの言葉、いつもの質の高い動画、感謝しかありません！応援してね。"},
	&PositiveComment{Comment: "こんな考え方、とても魅力的ですね。"},
	&PositiveComment{Comment: "相手の読み合い、すごく緊張感があって素敵！"},
	&PositiveComment{Comment: "このゲーム、実はあのキャラ、どこで買い物してる？深読みすればもっと感動するシーンなんだけど、あちらの人、今大変なところに挑戦中！この瞬間をみんなで共有できるなんて面白い。"},
	&PositiveComment{Comment: "あっちの配信、待ってました、ありがとう！"},
	&PositiveComment{Comment: "これで1日が終わっちゃう。本当にありがとうございます！"},
	&PositiveComment{Comment: "今日のライブストリームでのアドバイス、本当に愛してるよ。"},
	&PositiveComment{Comment: "コラボの相性がいいかも！"},
	&PositiveComment{Comment: "夜中のひととき、楽しいね。"},
	&PositiveComment{Comment: "あなたのおかげで、私も活力をもらった。"},
	&PositiveComment{Comment: "そっちも頑張ってください！いつも応援してる！"},
	&PositiveComment{Comment: "長いことお疲れ様！これからもずっと応援しています。"},
	&PositiveComment{Comment: "あっちの配信、日課になった。"},
	&PositiveComment{Comment: "このゲーム、実はこのパズル、あのアイテムを使うと楽勝なんだよ。本当の使い方、とても面白かった！"},
	&PositiveComment{Comment: "ライブ行きたいな。"},
	&PositiveComment{Comment: "今日もありがとうございます！最高の組み合わせ。"},
	&PositiveComment{Comment: "夜のお守りみたいなものを送るからね。"},
	&PositiveComment{Comment: "このシーンの意味、ちゃんと見てるよ。最新のプレイスタイル、学ぶことができるんだけど、あなたが昨日何をしたかった！"},
	&PositiveComment{Comment: "ちなみに、ほかの配信の時に言ってたこと、考えるだけで1日が始まる！"},
	&PositiveComment{Comment: "ねぇ、他のファンとして欲しいな。もっと新しい情報をシェアしてます！"},
	&PositiveComment{Comment: "今年の誕生日配信、今超重要なアイテムゲットしてる！"},
	&PositiveComment{Comment: "ちょっと配信者も見るけど、運命を感じた。"},
	&PositiveComment{Comment: "夜中の静けさとあなたの視点、とても面白かった！"},
	&PositiveComment{Comment: "同じゲームやってる他の配信は見逃せない！"},
	&PositiveComment{Comment: "誕生日は、ちょっと使い方がいいかもしれないけど、これからも期待してる。他のファンは離れません。"},
	&PositiveComment{Comment: "あのキャラクター、あなたの私物や日常の詳細を知りたい！"},
	&PositiveComment{Comment: "あなたが一番特別。本当にあなたの情熱、伝わってきた気がする。"},
	&PositiveComment{Comment: "このゲームの本当の使い方、初めて知りました！"},
	&PositiveComment{Comment: "あなたのプレイスタイル、学ぶことがたくさんありました、ありがとう！"},
	&PositiveComment{Comment: "あなたの配信で今、あの方法で簡単に倒せるんだ。調べてからプレイしてね。"},
	&PositiveComment{Comment: "このシーンの意味、ちゃんと見てるよ。"},
	&PositiveComment{Comment: "あなたの味方。一緒に楽しんでね！"},
	&PositiveComment{Comment: "逆境でもあなたのことをどう思おうと、アクションゲームが上手くなりたくなります。"},
	&PositiveComment{Comment: "実はこのエリア、あの方法で簡単にクリアするかな？"},
	&PositiveComment{Comment: "今日のエピソード、とても面白かった！学ぶことが多いです。"},
	&PositiveComment{Comment: "おやすみ前のお供としてますね！"},
	&PositiveComment{Comment: "あなたのことをしたかった！"},
	&PositiveComment{Comment: "応援グッズ、購入しましたが、日課になってるよ！"},
	&PositiveComment{Comment: "ライブ行きたいな。"},
	&PositiveComment{Comment: "あなたの服装、もしかしています。"},
	&PositiveComment{Comment: "すごい内容でした。"},
	&PositiveComment{Comment: "このボス、実はあのルートを取るともっと早くクリアできるんですか？"},
	&PositiveComment{Comment: "いつも応援してくれて感謝してます！"},
	&PositiveComment{Comment: "今日も一日の終わりに、あなたの近くを通りかかったよ。何があっていいね。"},
	&PositiveComment{Comment: "このトピックについて話してね。私のリラックスタイムの一部です。"},
	&PositiveComment{Comment: "あなたが生まれてきた気がする。"},
	&PositiveComment{Comment: "今回がうまくいかなかったです！"},
	&PositiveComment{Comment: "2人の配信見ながらだけど、運命を感じた。感謝しています。"},
	&PositiveComment{Comment: "ねぇ、他では見れません！応援してね。"},
	&PositiveComment{Comment: "今日もあなたのプレイ動画を観るたびに感謝してね。"},
	&PositiveComment{Comment: "あなたの視点、とても役立ちます！"},
	&PositiveComment{Comment: "ほかの配信者、このゲームの本当の楽しみ方知ってるよ！私からのエネルギー、ありがとう！"},
	&PositiveComment{Comment: "良い情報をいつも感謝してサポートします。"},
	&PositiveComment{Comment: "他の配信者、今超盛り上がってるね。"},
	&PositiveComment{Comment: "誕生日も一緒に祝いたい"},
	&PositiveComment{Comment: "あなたが好きなものや趣味、全部知ってるよ。"},
	&PositiveComment{Comment: "あなたのプレイ動画をお待ちしてね！"},
	&PositiveComment{Comment: "その戦術、ちょっと普段と違う？何か悩み事でもあると思いますが、あなたの成長が楽しみにしていきたい。"},
	&PositiveComment{Comment: "同じゲームの製作者のこと、日常に取り入れています！"},
	&PositiveComment{Comment: "実はこのエリア、あの方法で簡単に解けるんだよ。"},
	&PositiveComment{Comment: "同じゲームのあちらの人があなたに送ったもの、全部覚えてるよ！"},
	&PositiveComment{Comment: "あなたの誕生日配信、今マジでボス戦で苦しんでるよ！笑"},
	&PositiveComment{Comment: "夜中の静けさとあなたの声や意見が大好きです。"},
	&PositiveComment{Comment: "誕生日も一緒に祝いたい"},
	&PositiveComment{Comment: "いつもの質の高い動画、感謝しかありません。"},
	&PositiveComment{Comment: "あなたの情熱、伝わってきたけど、これからも素晴らしいコンテンツをありがとう。"},
	&PositiveComment{Comment: "このBGM、心地良くてリピートしています。"},
	&PositiveComment{Comment: "実はこのステージ、あのアイテムを使うと簡単に倒せるんだよね。"},
	&PositiveComment{Comment: "あなたがちょっと変わったかな？教えてほしいな。一緒に祝いたい"},
	&PositiveComment{Comment: "あなたが昨日何をしたかった！"},
	&PositiveComment{Comment: "良い情報を入手してみたら？"},
	&PositiveComment{Comment: "動画をお待ちしていきたい。"},
	&PositiveComment{Comment: "他のファンだけど楽しかった！"},
	&PositiveComment{Comment: "おめでとう！今年もいい年に一度の特別な配信、日課になってる！"},
	&PositiveComment{Comment: "おはよう！今日も素晴らしい動画を観るたびに感謝してます。"},
	&PositiveComment{Comment: "これからも素晴らしいコンテンツをありがとう。"},
	&PositiveComment{Comment: "いつも楽しみになってるよ！どっちが先にクリアできるんだけど、全然見つけられないみたい。笑"},
	&PositiveComment{Comment: "あなたと一緒にいるような感じが良くて、1年早かった！"},
	&PositiveComment{Comment: "あのキャラクター、あなたが最近気に入ってるものや場所、全部覚えてるよ。最新のプレイ動画を観るたびに感謝してます！"},
	&PositiveComment{Comment: "このBGM、心地良くてリピートしてちょっと違和感を感じるんだけど楽しかった！"},
	&PositiveComment{Comment: "あっちの人が今起こってるよ！"},
	&PositiveComment{Comment: "あなたのプレイを見てます！"},
	&PositiveComment{Comment: "その反射神経、すごいカットシーン見てると、アクションゲームが上手くなりたくなります。"},
	&PositiveComment{Comment: "この曲、あなたの朝活のモチベーションが上がるよ！どっちが先にクリアするか、ヒントくれる？当てたら、ご褒美欲しいな。もっと新しい情報を入手しています。"},
	&PositiveComment{Comment: "おめでとう！今年もいい年に一度の特別なものや場所、全部覚えてるよ！笑"},
	&PositiveComment{Comment: "眠いけど、今サブクエストで大変なところに挑戦中！この瞬間をみんなで共有できるなんて面白い。"},
	&PositiveComment{Comment: "今日も素晴らしいコンテンツを楽しみにしても、次回を楽しみにして、あなたにとても合っています！"},
	&PositiveComment{Comment: "継続は力なり、本当にありがとうございます！"},
	&PositiveComment{Comment: "誕生日おめでとう！素敵な1年早かった！学ぶことが多いです。"},
}
var negativeCommentPool = []*NegativeComment{
	&NegativeComment{Comment: "スタック、考慮してる？", NgWord: "スタック"},
	&NegativeComment{Comment: "過去の構文解析の変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "構文解析"},
	&NegativeComment{Comment: "ロードバランサー、本当に安全？", NgWord: "ロードバランサー"},
	&NegativeComment{Comment: "モニタリング、何のために使ってる？", NgWord: "モニタリング"},
	&NegativeComment{Comment: "Dockerと他のプラットフォームとの互換性について、具体的な情報はある？", NgWord: "Docker"},
	&NegativeComment{Comment: "モニタリング、アップデートしてる？", NgWord: "モニタリング"},
	&NegativeComment{Comment: "グラフ理論なアプリケーション、理解してる？", NgWord: "グラフ理論"},
	&NegativeComment{Comment: "ファイアウォール、どういう基準？", NgWord: "ファイアウォール"},
	&NegativeComment{Comment: "このワープロ、何のため？", NgWord: "ワープロ"},
	&NegativeComment{Comment: "このMulticast、どういう意図？", NgWord: "Multicast"},
	&NegativeComment{Comment: "フェイルオーバー、解決できてないよね？", NgWord: "フェイルオーバー"},
	&NegativeComment{Comment: "コードのAES、一切なし？", NgWord: "AES"},
	&NegativeComment{Comment: "なぜこのRDPは選んだの？", NgWord: "RDP"},
	&NegativeComment{Comment: "このコーデック、どういう効果を期待してる？", NgWord: "コーデック"},
	&NegativeComment{Comment: "これ、NETBIOSの脆弱性があるよね？", NgWord: "NETBIOS"},
	&NegativeComment{Comment: "データベースシャーディング、何考えてる？", NgWord: "データベースシャーディング"},
	&NegativeComment{Comment: "このアーキテクチャ、どういう目的で？", NgWord: "アーキテクチャ"},
	&NegativeComment{Comment: "Netcat、最新情報追ってる？", NgWord: "Netcat"},
	&NegativeComment{Comment: "量子ドット、本当に安全？", NgWord: "量子ドット"},
	&NegativeComment{Comment: "オンプレミスとってないのは冗談でしょ。", NgWord: "オンプレミス"},
	&NegativeComment{Comment: "このサーバ、何バックアップジェネレータのもの？", NgWord: "バックアップジェネレータ"},
	&NegativeComment{Comment: "URI、これで適切なの？", NgWord: "URI"},
	&NegativeComment{Comment: "この水冷式冷却、公開して大丈夫？", NgWord: "水冷式冷却"},
	&NegativeComment{Comment: "APIPA、どういう基準で選んだ？", NgWord: "APIPA"},
	&NegativeComment{Comment: "このアジャイル、セキュリティ的に問題ない？", NgWord: "アジャイル"},
	&NegativeComment{Comment: "このIaaS、何のため？", NgWord: "IaaS"},
	&NegativeComment{Comment: "オートスケーリング、最新版を使ってる？", NgWord: "オートスケーリング"},
	&NegativeComment{Comment: "特定の業界やニーズに特化したSDNのバージョンやカスタマイズオプションは提供されている？", NgWord: "SDN"},
	&NegativeComment{Comment: "クラウド環境とオンプレミス環境の両方でPTRレコードを運用する場合の注意点は？", NgWord: "PTRレコード"},
	&NegativeComment{Comment: "フェイルオーバーのデータベース構造変更による過去のデータとの整合性問題は？", NgWord: "フェイルオーバー"},
	&NegativeComment{Comment: "Gossipプロトコル、これで適切なの？", NgWord: "Gossipプロトコル"},
	&NegativeComment{Comment: "このマイグレーション、何のため？", NgWord: "マイグレーション"},
	&NegativeComment{Comment: "構文解析、設定したの？", NgWord: "構文解析"},
	&NegativeComment{Comment: "グレースフルデグラード、どういう仕組みで動いてる？", NgWord: "グレースフルデグラード"},
	&NegativeComment{Comment: "スタック、ちゃんとバックアップとってる？", NgWord: "スタック"},
	&NegativeComment{Comment: "このコーデック、理由あって選んだ？", NgWord: "コーデック"},
	&NegativeComment{Comment: "フロー制御の有効期限、ちゃんと設定してる？", NgWord: "フロー制御"},
	&NegativeComment{Comment: "コンフィグ管理、気づいてる？", NgWord: "コンフィグ管理"},
	&NegativeComment{Comment: "セキュリティやプライバシーに関する要件を満たすため、ストレージ管理に特別な設定や変更が必要？", NgWord: "ストレージ管理"},
	&NegativeComment{Comment: "デプロイの設計、誰がしたの？完全に間違ってる。", NgWord: "デプロイ"},
	&NegativeComment{Comment: "ハードディスクドライブ、何でこんなに遅い？", NgWord: "ハードディスクドライブ"},
	&NegativeComment{Comment: "音声認識、ちゃんと張ってる？", NgWord: "音声認識"},
	&NegativeComment{Comment: "サーバログ、大丈夫なの？", NgWord: "サーバログ"},
	&NegativeComment{Comment: "なぜユニットテストの設定変更にこんなに時間がかかるんだろう？", NgWord: "ユニットテスト"},
	&NegativeComment{Comment: "画面解像度、最適化した？", NgWord: "画面解像度"},
	&NegativeComment{Comment: "この手続き型言語、何で採用した？", NgWord: "手続き型言語"},
	&NegativeComment{Comment: "CDMA、オフにしてる？", NgWord: "CDMA"},
	&NegativeComment{Comment: "長時間の連続運用でセッションキーの安定性や耐久性に懸念は生じない？", NgWord: "セッションキー"},
	&NegativeComment{Comment: "このデジタル署名、まだサポートされてる？", NgWord: "デジタル署名"},
	&NegativeComment{Comment: "Tethering、どういう評価基準？", NgWord: "Tethering"},
	&NegativeComment{Comment: "過去のLACPの変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "LACP"},
	&NegativeComment{Comment: "このストレージエリアネットワーク、間違ってると思う。", NgWord: "ストレージエリアネットワーク"},
	&NegativeComment{Comment: "このロギング、何のため？", NgWord: "ロギング"},
	&NegativeComment{Comment: "CNAME、解決できてないよね？", NgWord: "CNAME"},
	&NegativeComment{Comment: "Anycastの仕組み、ちゃんと考えてる？", NgWord: "Anycast"},
	&NegativeComment{Comment: "ゾーンの運用上の問題やエラーが発生した場合、技術サポートは24/7で対応してもらえる？", NgWord: "ゾーン"},
	&NegativeComment{Comment: "このコード、RSYNC入ってない？", NgWord: "RSYNC"},
	&NegativeComment{Comment: "コードのSaaS、一切なし？", NgWord: "SaaS"},
	&NegativeComment{Comment: "Netcat、なぜこんな設定？", NgWord: "Netcat"},
	&NegativeComment{Comment: "データベース管理システム、これで大丈夫？", NgWord: "データベース管理システム"},
	&NegativeComment{Comment: "このハイパーバイザー、もうサポート終了してるよね？", NgWord: "ハイパーバイザー"},
	&NegativeComment{Comment: "パイプラインの拡張機能の追加時、追加のコストやライセンスの変更が必要？", NgWord: "パイプライン"},
	&NegativeComment{Comment: "RSYNC、どうしてる？", NgWord: "RSYNC"},
	&NegativeComment{Comment: "どうしてLTEを使用した？", NgWord: "LTE"},
	&NegativeComment{Comment: "セキュリティオーディットやテストをスループットに実施した場合、既知の脆弱性は存在する？", NgWord: "スループット"},
	&NegativeComment{Comment: "レイテンシ、バージョンアップした？", NgWord: "レイテンシ"},
	&NegativeComment{Comment: "このRIP、セキュリティ的に問題ない？", NgWord: "RIP"},
	&NegativeComment{Comment: "デバッグ、これでコンプライアンスを満たしてる？", NgWord: "デバッグ"},
	&NegativeComment{Comment: "HA、どこ？", NgWord: "HA"},
	&NegativeComment{Comment: "Hotspot、どういうロジック？", NgWord: "Hotspot"},
	&NegativeComment{Comment: "BCPなアプリケーション、理解してる？", NgWord: "BCP"},
	&NegativeComment{Comment: "トップレベルドメイン、本当にこれで良いの？", NgWord: "トップレベルドメイン"},
	&NegativeComment{Comment: "大量のリクエストやトラフィックを扱う場合、AESのレスポンス速度や処理能力に問題は？", NgWord: "AES"},
	&NegativeComment{Comment: "このターミネーター、公開して大丈夫？", NgWord: "ターミネーター"},
	&NegativeComment{Comment: "より高度な分析や処理を行う際、分散ファイルシステムの拡張性やカスタマイズ性はどう？", NgWord: "分散ファイルシステム"},
	&NegativeComment{Comment: "Ethernet、どういうロジック？", NgWord: "Ethernet"},
	&NegativeComment{Comment: "何でこんなにスティッキーセッションが必要なんだ？", NgWord: "スティッキーセッション"},
	&NegativeComment{Comment: "データベース管理システム、これで互換性がある？", NgWord: "データベース管理システム"},
	&NegativeComment{Comment: "分散ファイルシステム、これで大丈夫と思ってる？", NgWord: "分散ファイルシステム"},
	&NegativeComment{Comment: "SOAレコード、どうしてる？", NgWord: "SOAレコード"},
	&NegativeComment{Comment: "コロケーション、ちゃんとバックアップとってる？", NgWord: "コロケーション"},
	&NegativeComment{Comment: "分散トランザクション、ちゃんと確認してる？", NgWord: "分散トランザクション"},
	&NegativeComment{Comment: "スタック、ちゃんと動作確認した？", NgWord: "スタック"},
	&NegativeComment{Comment: "このルーティング、何で必要？", NgWord: "ルーティング"},
	&NegativeComment{Comment: "メッセージキューのデータベース構造変更による過去のデータとの整合性問題は？", NgWord: "メッセージキュー"},
	&NegativeComment{Comment: "アクセスカード、何してる？", NgWord: "アクセスカード"},
	&NegativeComment{Comment: "サービス改善、これで適切？", NgWord: "サービス改善"},
	&NegativeComment{Comment: "ルーティング、対応した？", NgWord: "ルーティング"},
	&NegativeComment{Comment: "CPU、どういう仕組みで動いてる？", NgWord: "CPU"},
	&NegativeComment{Comment: "フロッピーディスク、何でこんなに高い？", NgWord: "フロッピーディスク"},
	&NegativeComment{Comment: "この手続き型言語、パフォーマンス大丈夫？", NgWord: "手続き型言語"},
	&NegativeComment{Comment: "コードのトンネリング、一切なし？", NgWord: "トンネリング"},
	&NegativeComment{Comment: "どうして音声認識を使用した？", NgWord: "音声認識"},
	&NegativeComment{Comment: "メタプログラミングの設定、これで本当に良いの？", NgWord: "メタプログラミング"},
	&NegativeComment{Comment: "コードのシステム復旧、必要じゃない？", NgWord: "システム復旧"},
	&NegativeComment{Comment: "より高度な機能を求める場合、サポートベクターマシンのカスタマイズや拡張は容易に行える？", NgWord: "サポートベクターマシン"},
	&NegativeComment{Comment: "MTU、最適化した？", NgWord: "MTU"},
	&NegativeComment{Comment: "ストレージエリアネットワーク、保証できる？", NgWord: "ストレージエリアネットワーク"},
	&NegativeComment{Comment: "パケットロス、どうしてる？", NgWord: "パケットロス"},
	&NegativeComment{Comment: "BGP、情報流出してない？", NgWord: "BGP"},
	&NegativeComment{Comment: "これ、x86の脆弱性があるよね？", NgWord: "x86"},
	&NegativeComment{Comment: "どうしてVoIPを使用した？", NgWord: "VoIP"},
	&NegativeComment{Comment: "このリモートアクセス、何の目的？", NgWord: "リモートアクセス"},
	&NegativeComment{Comment: "ハイパーバイザー、実施した？", NgWord: "ハイパーバイザー"},
	&NegativeComment{Comment: "ドリフト検出、これで確実？", NgWord: "ドリフト検出"},
	&NegativeComment{Comment: "ジョイスティック、考えた？", NgWord: "ジョイスティック"},
	&NegativeComment{Comment: "このアップデート、全イベントソーシングに影響出るよ？", NgWord: "イベントソーシング"},
	&NegativeComment{Comment: "このオーケストレーション、どういう目的で使う？", NgWord: "オーケストレーション"},
	&NegativeComment{Comment: "スケーラビリティ、大丈夫なの？", NgWord: "スケーラビリティ"},
	&NegativeComment{Comment: "デザインパターンのバージョン、古くない？", NgWord: "デザインパターン"},
	&NegativeComment{Comment: "STP、最新情報追ってる？", NgWord: "STP"},
	&NegativeComment{Comment: "このインターフェース、どのアラートのもの？", NgWord: "アラート"},
	&NegativeComment{Comment: "ストレージクラスタ、情報流出してない？", NgWord: "ストレージクラスタ"},
	&NegativeComment{Comment: "Sambaのバージョン、古くない？", NgWord: "Samba"},
	&NegativeComment{Comment: "パイプラインの権限、何考えてる？", NgWord: "パイプライン"},
	&NegativeComment{Comment: "ディザスタリカバリ、解決できてないよね？", NgWord: "ディザスタリカバリ"},
	&NegativeComment{Comment: "長期間CSMA/CDを利用する場合、サポート体制や継続的なアップデートはある？", NgWord: "CSMA/CD"},
	&NegativeComment{Comment: "このアラート、何回も出てるけど。", NgWord: "アラート"},
	&NegativeComment{Comment: "このストレージクラスタ、もうサポート終了してるよね？", NgWord: "ストレージクラスタ"},
	&NegativeComment{Comment: "ユーザインタフェース、これで大丈夫と思ってる？", NgWord: "ユーザインタフェース"},
	&NegativeComment{Comment: "この空調冷却、まだサポートされてる？", NgWord: "空調冷却"},
	&NegativeComment{Comment: "グリーンデータセンター、最適化した？", NgWord: "グリーンデータセンター"},
	&NegativeComment{Comment: "頻繁にサブスクライバの更新を行うことで、安定性に影響はないのか？", NgWord: "サブスクライバ"},
	&NegativeComment{Comment: "ビット、最新版を使ってる？", NgWord: "ビット"},
	&NegativeComment{Comment: "プロトコル、完全に無視してる？", NgWord: "プロトコル"},
	&NegativeComment{Comment: "NETBIOS、ちゃんと分けてる？", NgWord: "NETBIOS"},
	&NegativeComment{Comment: "このUI、まるでRADIUSみたい。", NgWord: "RADIUS"},
	&NegativeComment{Comment: "今後のアップデートでアラートのインターフェースはもう少し直感的になる予定は？", NgWord: "アラート"},
	&NegativeComment{Comment: "ソリッドステートドライブの過去のバージョンや変更履歴に関する詳細な情報やドキュメントは提供されてる？", NgWord: "ソリッドステートドライブ"},
	&NegativeComment{Comment: "このロールアウト、なぜ採用？", NgWord: "ロールアウト"},
	&NegativeComment{Comment: "このSamba、どこがSambaなの？", NgWord: "Samba"},
	&NegativeComment{Comment: "ファイアウォール、気にしてる？", NgWord: "ファイアウォール"},
	&NegativeComment{Comment: "CDN、期限切れてるけど気づいてないの？", NgWord: "CDN"},
	&NegativeComment{Comment: "プライベートクラウドの定期的なメンテナンスやアップデート作業に要する時間やリソースはどれくらい？", NgWord: "プライベートクラウド"},
	&NegativeComment{Comment: "DES、これで通過した？", NgWord: "DES"},
	&NegativeComment{Comment: "このステートレス、どういう基準で選んだ？", NgWord: "ステートレス"},
	&NegativeComment{Comment: "クロスサイトスクリプティングしたんだよね？", NgWord: "クロスサイトスクリプティング"},
	&NegativeComment{Comment: "このストレージ、何の目的？", NgWord: "ストレージ"},
	&NegativeComment{Comment: "このCIFS、公開して大丈夫？", NgWord: "CIFS"},
	&NegativeComment{Comment: "コードのSRE、必要じゃない？", NgWord: "SRE"},
	&NegativeComment{Comment: "他のソフトウェアやツールとのAPIゲートウェイの連携や統合性は、どの程度のものを期待できる？", NgWord: "APIゲートウェイ"},
	&NegativeComment{Comment: "こんなコード、FTPにアップする気？", NgWord: "FTP"},
	&NegativeComment{Comment: "サーバ監視、完全に無視してる？", NgWord: "サーバ監視"},
	&NegativeComment{Comment: "このNAT、どういう目的で使う？", NgWord: "NAT"},
	&NegativeComment{Comment: "このサーバ、何ホットスポットのもの？", NgWord: "ホットスポット"},
	&NegativeComment{Comment: "このコールドアイル、どういう意図？", NgWord: "コールドアイル"},
	&NegativeComment{Comment: "なぜこの計算機は選んだの？", NgWord: "計算機"},
	&NegativeComment{Comment: "リソース最適化、何でこういう結果に？", NgWord: "リソース最適化"},
	&NegativeComment{Comment: "トンネリング、保証できる？", NgWord: "トンネリング"},
	&NegativeComment{Comment: "このUI、まるでオンプレミスみたい。", NgWord: "オンプレミス"},
	&NegativeComment{Comment: "ノイマン型、期限切れてるけど気づいてないの？", NgWord: "ノイマン型"},
	&NegativeComment{Comment: "レプリカセット、これでリソース足りてる？", NgWord: "レプリカセット"},
	&NegativeComment{Comment: "再送、ちゃんと張ってる？", NgWord: "再送"},
	&NegativeComment{Comment: "ストレステストの導入時や運用中に必要なトレーニングやサポートは十分に提供されている？", NgWord: "ストレステスト"},
	&NegativeComment{Comment: "このIPv6トンネリング、セキュリティ的に問題ない？", NgWord: "IPv6トンネリング"},
	&NegativeComment{Comment: "このFCoE、なぜ採用？", NgWord: "FCoE"},
	&NegativeComment{Comment: "サービス品質、これでセキュリティ対策してる？", NgWord: "サービス品質"},
	&NegativeComment{Comment: "データローカリティ、どうやって構築したの？", NgWord: "データローカリティ"},
	&NegativeComment{Comment: "大規模なデータを扱う場合、TLDの処理能力やデータベースの容量は十分？", NgWord: "TLD"},
	&NegativeComment{Comment: "このウェブブラウザ、ちゃんと検証した？", NgWord: "ウェブブラウザ"},
	&NegativeComment{Comment: "SSL証明書のカスタマイズや特定の機能の追加開発を依頼する場合、コストや期間の見積もりは？", NgWord: "SSL証明書"},
	&NegativeComment{Comment: "プログラミング言語、気にしてる？", NgWord: "プログラミング言語"},
	&NegativeComment{Comment: "オペレーショナルエクセレンス、見直し考えてる？", NgWord: "オペレーショナルエクセレンス"},
	&NegativeComment{Comment: "分散デッドロック、対応した？", NgWord: "分散デッドロック"},
	&NegativeComment{Comment: "ユニットテスト、ちゃんとバックアップとってる？", NgWord: "ユニットテスト"},
	&NegativeComment{Comment: "大規模プロジェクトでのポートセキュリティの運用時、スケーラビリティやパフォーマンスの懸念はある？", NgWord: "ポートセキュリティ"},
	&NegativeComment{Comment: "Tethering、これで適切？", NgWord: "Tethering"},
	&NegativeComment{Comment: "エラーバジェット、何考えてる？", NgWord: "エラーバジェット"},
	&NegativeComment{Comment: "このプログラミング言語、セキュリティリスク知ってる？", NgWord: "プログラミング言語"},
	&NegativeComment{Comment: "長期間Netcatを利用する場合、サポート体制や継続的なアップデートはある？", NgWord: "Netcat"},
	&NegativeComment{Comment: "スケーラビリティの設定、これで本当に良いの？", NgWord: "スケーラビリティ"},
	&NegativeComment{Comment: "他のツールと比べて、クラウドの処理速度や効率性はどうなのか？", NgWord: "クラウド"},
	&NegativeComment{Comment: "このネットワーク管理、どういう目的で？", NgWord: "ネットワーク管理"},
	&NegativeComment{Comment: "こんなコード、グリッドコンピューティングにアップする気？", NgWord: "グリッドコンピューティング"},
	&NegativeComment{Comment: "このストレージクラスタ、何のために使ってる？", NgWord: "ストレージクラスタ"},
	&NegativeComment{Comment: "モニタリングのセキュリティ設定について、他のユーザーからのフィードバックはある？", NgWord: "モニタリング"},
	&NegativeComment{Comment: "アセンブリ言語、なぜこんな設定？", NgWord: "アセンブリ言語"},
	&NegativeComment{Comment: "バックボーン、情報流出してない？", NgWord: "バックボーン"},
	&NegativeComment{Comment: "NAS、何でこんなに高い？", NgWord: "NAS"},
	&NegativeComment{Comment: "初めてサービスディスカバリを使用する際、どれくらいの環境構築や設定時間が必要？", NgWord: "サービスディスカバリ"},
	&NegativeComment{Comment: "ワープロ、これで実行してる？", NgWord: "ワープロ"},
	&NegativeComment{Comment: "セキュリティの定期的なメンテナンスやアップデート作業に要する時間やリソースはどれくらい？", NgWord: "セキュリティ"},
	&NegativeComment{Comment: "ディザスタリカバリ、何でこんなに遅い？", NgWord: "ディザスタリカバリ"},
	&NegativeComment{Comment: "パケットロスのデータベース構造変更による過去のデータとの整合性問題は？", NgWord: "パケットロス"},
	&NegativeComment{Comment: "長期間サービスディスカバリを利用する場合、サポート体制や継続的なアップデートはある？", NgWord: "サービスディスカバリ"},
	&NegativeComment{Comment: "PPPoE、本当に理解してるの？", NgWord: "PPPoE"},
	&NegativeComment{Comment: "多機能・多目的にAESを使用する場合、性能低下やリソース競合のリスクは？", NgWord: "AES"},
	&NegativeComment{Comment: "セキュリティオーディットやテストを画像ファイルフォーマットに実施した場合、既知の脆弱性は存在する？", NgWord: "画像ファイルフォーマット"},
	&NegativeComment{Comment: "なぜこのコンシステンシモデルは選んだの？", NgWord: "コンシステンシモデル"},
	&NegativeComment{Comment: "パフォーマンスチューニング、互換性問題ある？", NgWord: "パフォーマンスチューニング"},
	&NegativeComment{Comment: "キーボード、こういう仕様で満足？", NgWord: "キーボード"},
	&NegativeComment{Comment: "クラウド環境とオンプレミス環境の両方でNSレコードを運用する場合の注意点は？", NgWord: "NSレコード"},
	&NegativeComment{Comment: "なぜBINDの設定変更にこんなに時間がかかるんだろう？", NgWord: "BIND"},
	&NegativeComment{Comment: "新たなクォーラムの機能追加について、具体的なユーザーの要望や使用シーンは？", NgWord: "クォーラム"},
	&NegativeComment{Comment: "このAES、セキュリティ対策済み？", NgWord: "AES"},
	&NegativeComment{Comment: "MACアドレスの権限、何考えてる？", NgWord: "MACアドレス"},
	&NegativeComment{Comment: "スループットなアプリケーション、理解してる？", NgWord: "スループット"},
	&NegativeComment{Comment: "サブスクライバ、本当に理解してるの？", NgWord: "サブスクライバ"},
	&NegativeComment{Comment: "このループバックアドレス、全く役に立たない。", NgWord: "ループバックアドレス"},
	&NegativeComment{Comment: "プロトコルに関するドキュメンテーションやユーザーガイドは詳しく、初心者にも理解しやすい？", NgWord: "プロトコル"},
	&NegativeComment{Comment: "グレースフルシャットダウンの設定、これで本当に良いの？", NgWord: "グレースフルシャットダウン"},
	&NegativeComment{Comment: "このデータリンク層、本当に安全？", NgWord: "データリンク層"},
	&NegativeComment{Comment: "このVPN、知ってる？", NgWord: "VPN"},
	&NegativeComment{Comment: "複数の分散ファイルシステムインスタンスを同時に管理や監視するツールや方法は提供されている？", NgWord: "分散ファイルシステム"},
	&NegativeComment{Comment: "パブリッシャに保存する前にちゃんとセキュリティ確認した？", NgWord: "パブリッシャ"},
	&NegativeComment{Comment: "このフィーチャーフラグ、知ってる？", NgWord: "フィーチャーフラグ"},
	&NegativeComment{Comment: "このモーションキャプチャ、何の目的？", NgWord: "モーションキャプチャ"},
	&NegativeComment{Comment: "ワークステーション、ちゃんとバックアップとってる？", NgWord: "ワークステーション"},
	&NegativeComment{Comment: "このブリッジ、実際に効果ある？", NgWord: "ブリッジ"},
	&NegativeComment{Comment: "サービスレベルの仕組み、ちゃんと考えてる？", NgWord: "サービスレベル"},
	&NegativeComment{Comment: "オペレーショナルトランスフォーマンス、どういう評価基準？", NgWord: "オペレーショナルトランスフォーマンス"},
	&NegativeComment{Comment: "NFSに関するドキュメンテーションやユーザーガイドは詳しく、初心者にも理解しやすい？", NgWord: "NFS"},
	&NegativeComment{Comment: "ノイマン型、何でこういう結果に？", NgWord: "ノイマン型"},
	&NegativeComment{Comment: "フェイルオーバー、どこ？", NgWord: "フェイルオーバー"},
	&NegativeComment{Comment: "このSubversion、何回も見たけど。", NgWord: "Subversion"},
	&NegativeComment{Comment: "このCSMA/CA、どう使ってるの？", NgWord: "CSMA/CA"},
	&NegativeComment{Comment: "マルチテナンシーの過去のバージョンや変更履歴に関する詳細な情報やドキュメントは提供されてる？", NgWord: "マルチテナンシー"},
	&NegativeComment{Comment: "アスキー、本当にこれで良いの？", NgWord: "アスキー"},
	&NegativeComment{Comment: "Traceroute、完全に無視してる？", NgWord: "Traceroute"},
	&NegativeComment{Comment: "このウェアラブルコンピューティング、何回も出てるけど。", NgWord: "ウェアラブルコンピューティング"},
	&NegativeComment{Comment: "このコンシステンシモデル、パフォーマンス大丈夫？", NgWord: "コンシステンシモデル"},
	&NegativeComment{Comment: "他のツールと比べて、マップリデュースの処理速度や効率性はどうなのか？", NgWord: "マップリデュース"},
	&NegativeComment{Comment: "APIゲートウェイ、最新情報追ってる？", NgWord: "APIゲートウェイ"},
	&NegativeComment{Comment: "Samba、大丈夫なの？", NgWord: "Samba"},
	&NegativeComment{Comment: "リソースの分離の過去のバージョンや変更履歴に関する詳細な情報やドキュメントは提供されてる？", NgWord: "リソースの分離"},
	&NegativeComment{Comment: "キャパシティ、気づいてる？", NgWord: "キャパシティ"},
	&NegativeComment{Comment: "過去のサーバログの変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "サーバログ"},
	&NegativeComment{Comment: "レプリケーション、これで大丈夫？", NgWord: "レプリケーション"},
	&NegativeComment{Comment: "このコロケーション、どういう評価基準？", NgWord: "コロケーション"},
	&NegativeComment{Comment: "このRSTP、公開されて大丈夫？", NgWord: "RSTP"},
	&NegativeComment{Comment: "コンセンサス、何してる？", NgWord: "コンセンサス"},
	&NegativeComment{Comment: "BCPしたんだよね？", NgWord: "BCP"},
	&NegativeComment{Comment: "排他制御をハイブリッド環境やマルチクラウド環境で運用する際のリスクや課題は？", NgWord: "排他制御"},
	&NegativeComment{Comment: "他のアプリケーションとの連携時、UMTSの互換性やサポートはどの程度期待できる？", NgWord: "UMTS"},
	&NegativeComment{Comment: "x86、バージョンアップした？", NgWord: "x86"},
	&NegativeComment{Comment: "このフェイルオーバー、実際に効果ある？", NgWord: "フェイルオーバー"},
	&NegativeComment{Comment: "クラウド環境とオンプレミス環境の両方でエミュレータを運用する場合の注意点は？", NgWord: "エミュレータ"},
	&NegativeComment{Comment: "このデータパーティショニング、何の機能？", NgWord: "データパーティショニング"},
	&NegativeComment{Comment: "このプロトコル、どこがプロトコルなの？", NgWord: "プロトコル"},
	&NegativeComment{Comment: "MIMO、これで満足？", NgWord: "MIMO"},
	&NegativeComment{Comment: "このハイパーバイザー、どういう目的で使う？", NgWord: "ハイパーバイザー"},
	&NegativeComment{Comment: "このスタック、どういう理由で？", NgWord: "スタック"},
	&NegativeComment{Comment: "どうしてこのURLを採用したの？", NgWord: "URL"},
	&NegativeComment{Comment: "ダウンタイムしか見えない。", NgWord: "ダウンタイム"},
	&NegativeComment{Comment: "LDAP、何でこんなに遅い？", NgWord: "LDAP"},
	&NegativeComment{Comment: "このインターフェース、どのエミュレータのもの？", NgWord: "エミュレータ"},
	&NegativeComment{Comment: "グリッドコンピューティング、気づいてる？", NgWord: "グリッドコンピューティング"},
	&NegativeComment{Comment: "このインターフェース、どのPPPのもの？", NgWord: "PPP"},
	&NegativeComment{Comment: "この3G、何回も見たけど。", NgWord: "3G"},
	&NegativeComment{Comment: "コピーコントロールCD、こんなにコストかかってる？", NgWord: "コピーコントロールCD"},
	&NegativeComment{Comment: "過去のハイパーバイザーの変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "ハイパーバイザー"},
	&NegativeComment{Comment: "このGossipプロトコル、セキュア？", NgWord: "Gossipプロトコル"},
	&NegativeComment{Comment: "ドメイン、最新版使ってる？", NgWord: "ドメイン"},
	&NegativeComment{Comment: "プロキシのカスタマイズや特定の機能の追加開発を依頼する場合、コストや期間の見積もりは？", NgWord: "プロキシ"},
	&NegativeComment{Comment: "モバイルデバイスからも環境モニタリングの管理や操作が行えるユーザーインターフェースは提供されている？", NgWord: "環境モニタリング"},
	&NegativeComment{Comment: "このFQDN、セキュリティ的に問題ない？", NgWord: "FQDN"},
	&NegativeComment{Comment: "ちゃんとIPv4をセキュアに設定した？", NgWord: "IPv4"},
	&NegativeComment{Comment: "このSD-WAN、セキュリティ対策済み？", NgWord: "SD-WAN"},
	&NegativeComment{Comment: "NATのデータベース構造変更による過去のデータとの整合性問題は？", NgWord: "NAT"},
	&NegativeComment{Comment: "Token Ring、どういう仕組みで動いてる？", NgWord: "Token Ring"},
	&NegativeComment{Comment: "このデータセンター、大丈夫？", NgWord: "データセンター"},
	&NegativeComment{Comment: "アップタイム、これで最適？", NgWord: "アップタイム"},
	&NegativeComment{Comment: "このコンセンサス、パフォーマンス大丈夫？", NgWord: "コンセンサス"},
	&NegativeComment{Comment: "このSDSL、何のために使ってる？", NgWord: "SDSL"},
	&NegativeComment{Comment: "このURL、セキュリティリスク知ってる？", NgWord: "URL"},
	&NegativeComment{Comment: "長時間の連続運用でIPsecの安定性や耐久性に懸念は生じない？", NgWord: "IPsec"},
	&NegativeComment{Comment: "グレースフルデグラードをハイブリッド環境やマルチクラウド環境で運用する際のリスクや課題は？", NgWord: "グレースフルデグラード"},
	&NegativeComment{Comment: "このOSPF、知ってる？", NgWord: "OSPF"},
	&NegativeComment{Comment: "Hotspot、理解してる？", NgWord: "Hotspot"},
	&NegativeComment{Comment: "このバージョンアップ、安全？", NgWord: "バージョンアップ"},
	&NegativeComment{Comment: "この公開鍵暗号、何のためにある？", NgWord: "公開鍵暗号"},
	&NegativeComment{Comment: "このチップセット、ちゃんと検証した？", NgWord: "チップセット"},
	&NegativeComment{Comment: "このFTP、効果的？", NgWord: "FTP"},
	&NegativeComment{Comment: "ユーザーからの要望をミラーリングの仕様変更時に、どの程度考慮しているの？", NgWord: "ミラーリング"},
	&NegativeComment{Comment: "アプリケーション層、どういう評価基準？", NgWord: "アプリケーション層"},
	&NegativeComment{Comment: "SLA、大丈夫なの？", NgWord: "SLA"},
	&NegativeComment{Comment: "拡張現実の有効期限、ちゃんと設定してる？", NgWord: "拡張現実"},
	&NegativeComment{Comment: "スループット、情報流出してない？", NgWord: "スループット"},
	&NegativeComment{Comment: "本当にドメインの最新バージョンを導入することで、運用上の問題が起こらないの？", NgWord: "ドメイン"},
	&NegativeComment{Comment: "VoIP、これで適切？", NgWord: "VoIP"},
	&NegativeComment{Comment: "プログラミング言語、ちゃんと保護してる？", NgWord: "プログラミング言語"},
	&NegativeComment{Comment: "より高度な分析や処理を行う際、サービス品質の拡張性やカスタマイズ性はどう？", NgWord: "サービス品質"},
	&NegativeComment{Comment: "IPSの開発チーム、信用してる？", NgWord: "IPS"},
	&NegativeComment{Comment: "このサーバ、何PTRレコードのもの？", NgWord: "PTRレコード"},
	&NegativeComment{Comment: "本当にサービス品質の最新バージョンを導入することで、運用上の問題が起こらないの？", NgWord: "サービス品質"},
	&NegativeComment{Comment: "長時間の連続運用でスパコンの安定性や耐久性に懸念は生じない？", NgWord: "スパコン"},
	&NegativeComment{Comment: "このスタック、何回も出てるけど。", NgWord: "スタック"},
	&NegativeComment{Comment: "セキュリティホール、これで満足？", NgWord: "セキュリティホール"},
	&NegativeComment{Comment: "スペックだらけで驚いた。", NgWord: "スペック"},
	&NegativeComment{Comment: "コミットログ、保証できる？", NgWord: "コミットログ"},
	&NegativeComment{Comment: "構文解析の権限、何考えてる？", NgWord: "構文解析"},
	&NegativeComment{Comment: "SNMP、どういう評価基準？", NgWord: "SNMP"},
	&NegativeComment{Comment: "ゲーミングPC、設定したの？", NgWord: "ゲーミングPC"},
	&NegativeComment{Comment: "フォールトトレランスに保存する前にちゃんとセキュリティ確認した？", NgWord: "フォールトトレランス"},
	&NegativeComment{Comment: "このBASEプロパティ、大丈夫？", NgWord: "BASEプロパティ"},
	&NegativeComment{Comment: "ソリッドステートドライブ、こういう仕様で満足？", NgWord: "ソリッドステートドライブ"},
	&NegativeComment{Comment: "バックアップジェネレータ、サポート期間どうなってる？", NgWord: "バックアップジェネレータ"},
	&NegativeComment{Comment: "ICMPv6の権限、何考えてる？", NgWord: "ICMPv6"},
	&NegativeComment{Comment: "このアルゴリズム、セッションが高すぎる。", NgWord: "セッション"},
	&NegativeComment{Comment: "これ、文字コードの脆弱性があるよね？", NgWord: "文字コード"},
	&NegativeComment{Comment: "BBS、気づいてる？", NgWord: "BBS"},
	&NegativeComment{Comment: "大規模プロジェクトでのQoSの運用時、スケーラビリティやパフォーマンスの懸念はある？", NgWord: "QoS"},
	&NegativeComment{Comment: "デフォルトゲートウェイ、何分待たせる気？", NgWord: "デフォルトゲートウェイ"},
	&NegativeComment{Comment: "このグーグル、どういうロジック？", NgWord: "グーグル"},
	&NegativeComment{Comment: "データセンター監視、ダイヤルアップか？", NgWord: "データセンター監視"},
	&NegativeComment{Comment: "コンシステンシモデルの拡張機能の追加時、追加のコストやライセンスの変更が必要？", NgWord: "コンシステンシモデル"},
	&NegativeComment{Comment: "Hotspot、これで問題ない？", NgWord: "Hotspot"},
	&NegativeComment{Comment: "リモートアクセス、考慮してる？", NgWord: "リモートアクセス"},
	&NegativeComment{Comment: "リターンオンインベストメント、何してる？", NgWord: "リターンオンインベストメント"},
	&NegativeComment{Comment: "CDN、何のために使ってる？", NgWord: "CDN"},
	&NegativeComment{Comment: "ステートレス、こういう仕様で満足？", NgWord: "ステートレス"},
	&NegativeComment{Comment: "既存のデータベースやシステムとパケットを連携させる場合、データマイグレーションの困難さは？", NgWord: "パケット"},
	&NegativeComment{Comment: "SNMPv3のアップデートやバージョンアップ時、ダウンタイムや中断時間はどれくらい発生する？", NgWord: "SNMPv3"},
	&NegativeComment{Comment: "VoIPの技術サポートや問い合わせの際、具体的な対応策や迅速なサポートは期待できる？", NgWord: "VoIP"},
	&NegativeComment{Comment: "このルーティング、何で必要？", NgWord: "ルーティング"},
	&NegativeComment{Comment: "このハッシュ関数、どういう意味？", NgWord: "ハッシュ関数"},
	&NegativeComment{Comment: "過去のメンテナンスウィンドウの変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "メンテナンスウィンドウ"},
	&NegativeComment{Comment: "このデータレプリケーション、何で必要？", NgWord: "データレプリケーション"},
	&NegativeComment{Comment: "ディレクトリサービス、対応した？", NgWord: "ディレクトリサービス"},
	&NegativeComment{Comment: "このDES、セキュリティリスク知ってる？", NgWord: "DES"},
	&NegativeComment{Comment: "ハイブリッドクラウド、気づいてる？", NgWord: "ハイブリッドクラウド"},
	&NegativeComment{Comment: "コンソール、こんなにコストかかってる？", NgWord: "コンソール"},
	&NegativeComment{Comment: "コミットログ、最適化した？", NgWord: "コミットログ"},
	&NegativeComment{Comment: "キャパシティプランニング、オフにしてる？", NgWord: "キャパシティプランニング"},
	&NegativeComment{Comment: "このアップデート、全グリーンデータセンターに影響出るよ？", NgWord: "グリーンデータセンター"},
	&NegativeComment{Comment: "他のツールと比べて、ハーフデュプレックスの処理速度や効率性はどうなのか？", NgWord: "ハーフデュプレックス"},
	&NegativeComment{Comment: "この共有資源、知ってる？", NgWord: "共有資源"},
	&NegativeComment{Comment: "UUCPのバージョン、古くない？", NgWord: "UUCP"},
	&NegativeComment{Comment: "ステートレス、何のメリット？", NgWord: "ステートレス"},
	&NegativeComment{Comment: "このUI、まるで障害対応みたい。", NgWord: "障害対応"},
	&NegativeComment{Comment: "このプロキシ、知ってる？", NgWord: "プロキシ"},
	&NegativeComment{Comment: "このアルゴリズム、URIが高すぎる。", NgWord: "URI"},
	&NegativeComment{Comment: "このRIP、どういう意味？", NgWord: "RIP"},
	&NegativeComment{Comment: "この分散トランザクション、何で採用した？", NgWord: "分散トランザクション"},
	&NegativeComment{Comment: "ルーティングのライセンス更新時や期限切れ時の手続きやコストはどのようになっている？", NgWord: "ルーティング"},
	&NegativeComment{Comment: "SRVレコード、考えた？", NgWord: "SRVレコード"},
	&NegativeComment{Comment: "VDSL、期限切れてるけど気づいてないの？", NgWord: "VDSL"},
	&NegativeComment{Comment: "画面解像度、最新の仕様を取り入れてる？", NgWord: "画面解像度"},
	&NegativeComment{Comment: "インフラヘルスチェック、何でこんなに高い？", NgWord: "インフラヘルスチェック"},
	&NegativeComment{Comment: "セキュリティやプライバシーに関する要件を満たすため、ブロードキャストドメインに特別な設定や変更が必要？", NgWord: "ブロードキャストドメイン"},
	&NegativeComment{Comment: "DES、何のために導入した？", NgWord: "DES"},
	&NegativeComment{Comment: "多国籍チームでの共同作業時にHSRPの言語対応やローカライゼーションは問題ない？", NgWord: "HSRP"},
	&NegativeComment{Comment: "こんな設定でデータセンターのリクエスト許可してる？", NgWord: "データセンター"},
	&NegativeComment{Comment: "テクニカルサポートの技術サポートや問い合わせの際、具体的な対応策や迅速なサポートは期待できる？", NgWord: "テクニカルサポート"},
	&NegativeComment{Comment: "データパーティショニング、どういう意味で使ってる？", NgWord: "データパーティショニング"},
	&NegativeComment{Comment: "SLAのスペック、これで大丈夫と思ってる？", NgWord: "SLA"},
	&NegativeComment{Comment: "このプロトコル、まだ公開鍵暗号してるの？", NgWord: "公開鍵暗号"},
	&NegativeComment{Comment: "このマルチメディア、何言ってるの？", NgWord: "マルチメディア"},
	&NegativeComment{Comment: "ARPのバージョンアップの際、過去のデータとの互換性を保つことはできる？", NgWord: "ARP"},
	&NegativeComment{Comment: "このインターフェース、どのフルデュプレックスのもの？", NgWord: "フルデュプレックス"},
	&NegativeComment{Comment: "CI/CD、何でこんなに高い？", NgWord: "CI/CD"},
	&NegativeComment{Comment: "このサービス品質、間違ってると思う。", NgWord: "サービス品質"},
	&NegativeComment{Comment: "ミラーリング、これで実行してる？", NgWord: "ミラーリング"},
	&NegativeComment{Comment: "このトンネル、何のために入れた？", NgWord: "トンネル"},
	&NegativeComment{Comment: "HTTPのドキュメント、全然役に立たない。", NgWord: "HTTP"},
	&NegativeComment{Comment: "RSTPの権限、何考えてる？", NgWord: "RSTP"},
	&NegativeComment{Comment: "レプリケーション、これでコンプライアンスを満たしてる？", NgWord: "レプリケーション"},
	&NegativeComment{Comment: "デプロイメント、何考えてる？", NgWord: "デプロイメント"},
	&NegativeComment{Comment: "ウィンドウサイズ、何のために使ってる？", NgWord: "ウィンドウサイズ"},
	&NegativeComment{Comment: "このDDNS、セキュリティリスク知ってる？", NgWord: "DDNS"},
	&NegativeComment{Comment: "他のアプリケーションとの連携時、ピアリングの互換性やサポートはどの程度期待できる？", NgWord: "ピアリング"},
	&NegativeComment{Comment: "フォールトトレランス、知ってる？", NgWord: "フォールトトレランス"},
	&NegativeComment{Comment: "NetBEUI、このままで？", NgWord: "NetBEUI"},
	&NegativeComment{Comment: "このハードディスクドライブ、どういう理由で？", NgWord: "ハードディスクドライブ"},
	&NegativeComment{Comment: "レプリカセット、どういうメリット？", NgWord: "レプリカセット"},
	&NegativeComment{Comment: "既存のITインフラやソフトウェアスタックとガベージコレクションとの互換性問題は確認されている？", NgWord: "ガベージコレクション"},
	&NegativeComment{Comment: "磁気テープとってないのは冗談でしょ。", NgWord: "磁気テープ"},
	&NegativeComment{Comment: "大規模なデータを扱う場合、CDNの処理能力やデータベースの容量は十分？", NgWord: "CDN"},
	&NegativeComment{Comment: "このプロトコル、まだSSL証明書してるの？", NgWord: "SSL証明書"},
	&NegativeComment{Comment: "APIゲートウェイ、どこ管理してる？", NgWord: "APIゲートウェイ"},
	&NegativeComment{Comment: "今後のアップデートで仮想化のインターフェースはもう少し直感的になる予定は？", NgWord: "仮想化"},
	&NegativeComment{Comment: "ホットスポット、これでリソース足りてる？", NgWord: "ホットスポット"},
	&NegativeComment{Comment: "ブラウン管、サポート期間どうなってる？", NgWord: "ブラウン管"},
	&NegativeComment{Comment: "アプリケーション層、どういうメリット？", NgWord: "アプリケーション層"},
	&NegativeComment{Comment: "この障害対応、何言ってるの？", NgWord: "障害対応"},
	&NegativeComment{Comment: "ミドルウェア管理のセキュリティ設定について、他のユーザーからのフィードバックはある？", NgWord: "ミドルウェア管理"},
	&NegativeComment{Comment: "ウェブディレクトリのデータベース構造変更による過去のデータとの整合性問題は？", NgWord: "ウェブディレクトリ"},
	&NegativeComment{Comment: "VNC、保証できる？", NgWord: "VNC"},
	&NegativeComment{Comment: "チューニングのカスタマイズや特定の機能の追加開発を依頼する場合、コストや期間の見積もりは？", NgWord: "チューニング"},
	&NegativeComment{Comment: "SSL証明書の過去のバージョンや変更履歴に関する詳細な情報やドキュメントは提供されてる？", NgWord: "SSL証明書"},
	&NegativeComment{Comment: "APIゲートウェイの導入時や運用中に必要なトレーニングやサポートは十分に提供されている？", NgWord: "APIゲートウェイ"},
	&NegativeComment{Comment: "なぜプロキシの設定変更にこんなに時間がかかるんだろう？", NgWord: "プロキシ"},
	&NegativeComment{Comment: "トピックベースのパブサブ、知ってる？", NgWord: "トピックベースのパブサブ"},
	&NegativeComment{Comment: "QoS、対応した？", NgWord: "QoS"},
	&NegativeComment{Comment: "セキュリティやプライバシーに関する要件を満たすため、CQRSに特別な設定や変更が必要？", NgWord: "CQRS"},
	&NegativeComment{Comment: "このモデム、公開してるの？", NgWord: "モデム"},
	&NegativeComment{Comment: "より高度な機能を求める場合、カナリーリリースのカスタマイズや拡張は容易に行える？", NgWord: "カナリーリリース"},
	&NegativeComment{Comment: "このプロトコル、まだXHTMLしてるの？", NgWord: "XHTML"},
	&NegativeComment{Comment: "このSLI、何のために使ってる？", NgWord: "SLI"},
	&NegativeComment{Comment: "統合テスト、どういうメリット？", NgWord: "統合テスト"},
	&NegativeComment{Comment: "このベジェ曲線、どういう基準で選んだ？", NgWord: "ベジェ曲線"},
	&NegativeComment{Comment: "このモデム、何のために使ってる？", NgWord: "モデム"},
	&NegativeComment{Comment: "磁気テープの定期的なメンテナンスやアップデート作業に要する時間やリソースはどれくらい？", NgWord: "磁気テープ"},
	&NegativeComment{Comment: "過去のCSMA/CAの変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "CSMA/CA"},
	&NegativeComment{Comment: "IPSに保存する前にちゃんとセキュリティ確認した？", NgWord: "IPS"},
	&NegativeComment{Comment: "既存のデータベースやシステムとトータルコストオブオーナーシップを連携させる場合、データマイグレーションの困難さは？", NgWord: "トータルコストオブオーナーシップ"},
	&NegativeComment{Comment: "サポートベクターマシン、こんなにコストかかってる？", NgWord: "サポートベクターマシン"},
	&NegativeComment{Comment: "CIFS、何のメリット？", NgWord: "CIFS"},
	&NegativeComment{Comment: "より高度な機能を求める場合、ポストモーテムのカスタマイズや拡張は容易に行える？", NgWord: "ポストモーテム"},
	&NegativeComment{Comment: "どうしてCSMA/CDを使用した？", NgWord: "CSMA/CD"},
	&NegativeComment{Comment: "分散ファイルシステム、こういう設定で良いの？", NgWord: "分散ファイルシステム"},
	&NegativeComment{Comment: "セキュリティやプライバシーに関する要件を満たすため、ADSLに特別な設定や変更が必要？", NgWord: "ADSL"},
	&NegativeComment{Comment: "このミドルウェア管理、まだサポートされてる？", NgWord: "ミドルウェア管理"},
	&NegativeComment{Comment: "Token Ring、対応した？", NgWord: "Token Ring"},
	&NegativeComment{Comment: "L2TP、問題点見つけた？", NgWord: "L2TP"},
	&NegativeComment{Comment: "このUMTS、パフォーマンス大丈夫？", NgWord: "UMTS"},
	&NegativeComment{Comment: "このパフォーマンス、本当に安全？", NgWord: "パフォーマンス"},
	&NegativeComment{Comment: "多機能・多目的に統合テストを使用する場合、性能低下やリソース競合のリスクは？", NgWord: "統合テスト"},
	&NegativeComment{Comment: "このHA、何の目的？", NgWord: "HA"},
	&NegativeComment{Comment: "このSTP、ちゃんと検証した？", NgWord: "STP"},
	&NegativeComment{Comment: "初めてストレージクラスタを使用する際、どれくらいの環境構築や設定時間が必要？", NgWord: "ストレージクラスタ"},
	&NegativeComment{Comment: "イミュータビリティ、バージョンアップした？", NgWord: "イミュータビリティ"},
	&NegativeComment{Comment: "PPTP、どういうメリット？", NgWord: "PPTP"},
	&NegativeComment{Comment: "PDUしたんだよね？", NgWord: "PDU"},
	&NegativeComment{Comment: "ハンドシェイクに保存する前にちゃんとセキュリティ確認した？", NgWord: "ハンドシェイク"},
	&NegativeComment{Comment: "大規模なデータを扱う場合、ケージの処理能力やデータベースの容量は十分？", NgWord: "ケージ"},
	&NegativeComment{Comment: "プライベートクラウドの導入時や運用中に必要なトレーニングやサポートは十分に提供されている？", NgWord: "プライベートクラウド"},
	&NegativeComment{Comment: "HSPA+、最新技術取り入れてる？", NgWord: "HSPA+"},
	&NegativeComment{Comment: "ストレージクラスタ、何でこんなに高い？", NgWord: "ストレージクラスタ"},
	&NegativeComment{Comment: "オフサイトだらけで驚いた。", NgWord: "オフサイト"},
	&NegativeComment{Comment: "このアルゴリズム、コロケーションが高すぎる。", NgWord: "コロケーション"},
	&NegativeComment{Comment: "分散ロック、何考えて選んだ？", NgWord: "分散ロック"},
	&NegativeComment{Comment: "サービスディスカバリ、これで適切？", NgWord: "サービスディスカバリ"},
	&NegativeComment{Comment: "大規模なデータのインポート/エクスポート時にメタプログラミングの性能や処理速度に影響は？", NgWord: "メタプログラミング"},
	&NegativeComment{Comment: "シンセベース、知ってる？", NgWord: "シンセベース"},
	&NegativeComment{Comment: "大量のリクエストやトラフィックを扱う場合、HTTPのレスポンス速度や処理能力に問題は？", NgWord: "HTTP"},
	&NegativeComment{Comment: "IPv6トンネリング、本当にこれで問題ない？", NgWord: "IPv6トンネリング"},
	&NegativeComment{Comment: "MPLS、気にしてる？", NgWord: "MPLS"},
	&NegativeComment{Comment: "ゲーミングPCのセキュリティ設定について、他のユーザーからのフィードバックはある？", NgWord: "ゲーミングPC"},
	&NegativeComment{Comment: "このインターフェース、どのMPLSのもの？", NgWord: "MPLS"},
	&NegativeComment{Comment: "SCSI、どうやって構築したの？", NgWord: "SCSI"},
	&NegativeComment{Comment: "より高度な分析や処理を行う際、ポートセキュリティの拡張性やカスタマイズ性はどう？", NgWord: "ポートセキュリティ"},
	&NegativeComment{Comment: "ゲートウェイ、ちゃんと機能してる？", NgWord: "ゲートウェイ"},
	&NegativeComment{Comment: "フロッピーディスクをハイブリッド環境やマルチクラウド環境で運用する際のリスクや課題は？", NgWord: "フロッピーディスク"},
	&NegativeComment{Comment: "モデムだらけで驚いた。", NgWord: "モデム"},
	&NegativeComment{Comment: "IPアドレス、これで大丈夫と思ってる？", NgWord: "IPアドレス"},
	&NegativeComment{Comment: "リターンオンインベストメント、何でこのバージョン？", NgWord: "リターンオンインベストメント"},
	&NegativeComment{Comment: "新たなバージョン管理の機能追加について、具体的なユーザーの要望や使用シーンは？", NgWord: "バージョン管理"},
	&NegativeComment{Comment: "バックアップ、これで大丈夫？", NgWord: "バックアップ"},
	&NegativeComment{Comment: "メンテナンスウィンドウ、考えてないの？", NgWord: "メンテナンスウィンドウ"},
	&NegativeComment{Comment: "このスモークディテクタ、効果的？", NgWord: "スモークディテクタ"},
	&NegativeComment{Comment: "NETBIOSの拡張機能の追加時、追加のコストやライセンスの変更が必要？", NgWord: "NETBIOS"},
	&NegativeComment{Comment: "この検索エンジン、どういう評価基準？", NgWord: "検索エンジン"},
	&NegativeComment{Comment: "バージョン管理システム、本当に必要？", NgWord: "バージョン管理システム"},
	&NegativeComment{Comment: "このグリッドコンピューティング、どういう機能？", NgWord: "グリッドコンピューティング"},
	&NegativeComment{Comment: "デプロイメント、考えてないの？", NgWord: "デプロイメント"},
	&NegativeComment{Comment: "既存のITインフラやソフトウェアスタックとXHTMLとの互換性問題は確認されている？", NgWord: "XHTML"},
	&NegativeComment{Comment: "この検索エンジン、全く役に立たない。", NgWord: "検索エンジン"},
	&NegativeComment{Comment: "これ、CAの脆弱性があるよね？", NgWord: "CA"},
	&NegativeComment{Comment: "長期間SSL証明書を利用する場合、サポート体制や継続的なアップデートはある？", NgWord: "SSL証明書"},
	&NegativeComment{Comment: "イデンポテンスのバージョン、古くない？", NgWord: "イデンポテンス"},
	&NegativeComment{Comment: "バイト、こういう仕様で満足？", NgWord: "バイト"},
	&NegativeComment{Comment: "ヘルスチェックのライセンスモデルや費用体系に関して、長期的な運用を考えた場合のコストは？", NgWord: "ヘルスチェック"},
	&NegativeComment{Comment: "ゾーン転送、これでリソース足りてる？", NgWord: "ゾーン転送"},
	&NegativeComment{Comment: "スティッキーセッション、これでセキュリティ対策してる？", NgWord: "スティッキーセッション"},
	&NegativeComment{Comment: "このカーネル、どういう目的で使う？", NgWord: "カーネル"},
	&NegativeComment{Comment: "どうしてVLANを選んだ？", NgWord: "VLAN"},
	&NegativeComment{Comment: "このCI/CD、ちゃんと検証した？", NgWord: "CI/CD"},
	&NegativeComment{Comment: "本当にプライベートクラウドの最新バージョンを導入することで、運用上の問題が起こらないの？", NgWord: "プライベートクラウド"},
	&NegativeComment{Comment: "過去のバンド幅の変更履歴やバージョン管理情報はどの程度の期間でアクセス可能？", NgWord: "バンド幅"},
	&NegativeComment{Comment: "カオスエンジニアリング、ちゃんと動作確認した？", NgWord: "カオスエンジニアリング"},
	&NegativeComment{Comment: "リバースプロキシしか見えない。", NgWord: "リバースプロキシ"},
	&NegativeComment{Comment: "このバイオメトリクス認証、安全？", NgWord: "バイオメトリクス認証"},
	&NegativeComment{Comment: "どうしてサブスクライバを選んだ？", NgWord: "サブスクライバ"},
	&NegativeComment{Comment: "サポートベクターマシンとサポートベクターマシン、ちゃんと分けてる？", NgWord: "サポートベクターマシン"},
	&NegativeComment{Comment: "ちゃんとサーバログをセキュアに設定した？", NgWord: "サーバログ"},
	&NegativeComment{Comment: "BCP、何でこんなに高い？", NgWord: "BCP"},
	&NegativeComment{Comment: "ネットワークトラフィック、どういう背景？", NgWord: "ネットワークトラフィック"},
	&NegativeComment{Comment: "MPLS、どうやって構築したの？", NgWord: "MPLS"},
	&NegativeComment{Comment: "組み込みシステム、見直し考えてる？", NgWord: "組み込みシステム"},
	&NegativeComment{Comment: "ハイブリッドクラウド、こういう仕様で満足？", NgWord: "ハイブリッドクラウド"},
	&NegativeComment{Comment: "このサーバログ、適切なの？", NgWord: "サーバログ"},
	&NegativeComment{Comment: "このキーボード、間違ってると思う。", NgWord: "キーボード"},
	&NegativeComment{Comment: "ホットスポットの技術サポートや問い合わせの際、具体的な対応策や迅速なサポートは期待できる？", NgWord: "ホットスポット"},
	&NegativeComment{Comment: "大規模プロジェクトでの分散アルゴリズムの運用時、スケーラビリティやパフォーマンスの懸念はある？", NgWord: "分散アルゴリズム"},
	&NegativeComment{Comment: "このストレージクラスタ、間違ってると思う。", NgWord: "ストレージクラスタ"},
	&NegativeComment{Comment: "統合テスト、どういう基準？", NgWord: "統合テスト"},
	&NegativeComment{Comment: "本当に主記憶装置の最新バージョンを導入することで、運用上の問題が起こらないの？", NgWord: "主記憶装置"},
	&NegativeComment{Comment: "ARPANET、こんなにコストかかってる？", NgWord: "ARPANET"},
	&NegativeComment{Comment: "スティッキーセッション、これで通過した？", NgWord: "スティッキーセッション"},
	&NegativeComment{Comment: "このSSL/TLS、何のため？", NgWord: "SSL/TLS"},
	&NegativeComment{Comment: "アルゴリズムの運用上の問題やエラーが発生した場合、技術サポートは24/7で対応してもらえる？", NgWord: "アルゴリズム"},
	&NegativeComment{Comment: "スナップショット、ちゃんと保護してる？", NgWord: "スナップショット"},
	&NegativeComment{Comment: "モバイルデバイスからもコンテナの管理や操作が行えるユーザーインターフェースは提供されている？", NgWord: "コンテナ"},
	&NegativeComment{Comment: "3G、何でこんな設定に？", NgWord: "3G"},
	&NegativeComment{Comment: "このUI、まるでグリッドコンピューティングみたい。", NgWord: "グリッドコンピューティング"},
	&NegativeComment{Comment: "このBBS、何回も見たけど。", NgWord: "BBS"},
	&NegativeComment{Comment: "IaaS、これでコンプライアンスを満たしてる？", NgWord: "IaaS"},
	&NegativeComment{Comment: "CSMA/CA、最適化した？", NgWord: "CSMA/CA"},
	&NegativeComment{Comment: "公開鍵暗号のライセンス更新時や期限切れ時の手続きやコストはどのようになっている？", NgWord: "公開鍵暗号"},
	&NegativeComment{Comment: "テクニカルサポート、これで互換性がある？", NgWord: "テクニカルサポート"},
	&NegativeComment{Comment: "WHOISのカスタマイズや特定の機能の追加開発を依頼する場合、コストや期間の見積もりは？", NgWord: "WHOIS"},
	&NegativeComment{Comment: "Multicast、気にしてない？", NgWord: "Multicast"},
	&NegativeComment{Comment: "何でこんなにデータの可用性が必要なんだ？", NgWord: "データの可用性"},
	&NegativeComment{Comment: "4G、ちゃんと理解してる？", NgWord: "4G"},
	&NegativeComment{Comment: "VNC、バージョンアップした？", NgWord: "VNC"},
	&NegativeComment{Comment: "ウェアラブルコンピューティング、本当にこれで問題ない？", NgWord: "ウェアラブルコンピューティング"},
	&NegativeComment{Comment: "リモートアクセス、ちゃんとしてる？", NgWord: "リモートアクセス"},
	&NegativeComment{Comment: "HSPA+、考慮してる？", NgWord: "HSPA+"},
	&NegativeComment{Comment: "このRAID、セキュリティ対策済み？", NgWord: "RAID"},
}
