import random
import json

N = 1000

SQL_FORMAT = "\t({user_id}, {livestream_id}, '{comment}', UNIX_TIMESTAMP()),\n"

with open('./initial-data/autogenerated_user_livestream_foreignkey_pairs.json', 'r') as f:
    fk_pairs = json.loads(f.read().rstrip())

with open('./initial-data/positive_sentence.txt', 'r') as f:
    livecomments = list(line.rstrip() for line in f.readlines())

with open('/tmp/livecomments.sql', 'w') as f:
    f.write("INSERT INTO livecomments (user_id, livestream_id, comment, created_at)\n")
    f.write("VALUES\n")
    for _ in range(N):
        user_id, livestream_id = random.choice(fk_pairs)
        comment = random.choice(livecomments)
        sql = SQL_FORMAT.format(comment=comment, user_id=user_id, livestream_id=livestream_id)
        f.write(sql)
    user_id, livestream_id = random.choice(fk_pairs)
    f.write(f"\t({user_id}, {livestream_id}, 'こんにちは', UNIX_TIMESTAMP());\n")

