import random
import json

N = 10000


SQL_FORMAT = "\t('{emoji_name}', {user_id}, {livestream_id}, UNIX_TIMESTAMP()),\n"

with open('./initial-data/autogenerated_user_livestream_foreignkey_pairs.json', 'r') as f:
    fk_pairs = json.loads(f.read().rstrip())

with open('./initial-data/emoji.txt', 'r') as f:
    emoji_list = list(line.rstrip() for line in f.readlines())

with open('/tmp/reactions.sql', 'w') as f:
    f.write('INSERT INTO reactions (emoji_name, user_id, livestream_id, created_at)\n')
    f.write('VALUES\n')
    for _ in range(N):
        user_id, livestream_id = random.choice(fk_pairs)
        emoji_name = random.choice(emoji_list)
        sql = SQL_FORMAT.format(emoji_name=emoji_name, user_id=user_id, livestream_id=livestream_id)
        f.write(sql)

    user_id, livestream_id = random.choice(fk_pairs)
    f.write(f"\t('+1', {user_id}, {livestream_id}, UNIX_TIMESTAMP());\n")
