import random
import json

N = 1000


SQL_FORMAT = "\t('{emoji_name}', {user_id}, {livestream_id}, UNIX_TIMESTAMP()),\n"
GO_FORMAT= "\t&InitialReaction{{ UserID: {user_id}, LivestreamID: {livestream_id}, EmojiName: \"{emoji_name}\" }},\n"

with open('./initial-data/autogenerated_user_livestream_foreignkey_pairs.json', 'r') as f:
    fk_pairs = json.loads(f.read().rstrip())

with open('./initial-data/emoji.txt', 'r') as f:
    emoji_list = list(line.rstrip() for line in f.readlines())

sql_values = []
go_ctors = []
for _ in range(N):
    user_id, livestream_id = random.choice(fk_pairs)
    emoji_name = random.choice(emoji_list)
    sql = SQL_FORMAT.format(emoji_name=emoji_name, user_id=user_id, livestream_id=livestream_id)
    sql_values.append(sql)
    go_ctor = GO_FORMAT.format(user_id=user_id, livestream_id=livestream_id, emoji_name=emoji_name)
    go_ctors.append(go_ctor)
sql_values.append(f"\t('+1', {user_id}, {livestream_id}, UNIX_TIMESTAMP());\n")
go_ctors.append("\t&InitialReaction{{ UserID: {user_id}, LivestreamID: {livestream_id}, EmojiName: \"+1\" }},\n".format(user_id=user_id, livestream_id=livestream_id, emoji_name=emoji_name))

with open('/tmp/reactions.sql', 'w') as f:
    f.write('INSERT INTO reactions (emoji_name, user_id, livestream_id, created_at)\n')
    f.write('VALUES\n')
    for sql_value in sql_values:
        f.write(sql_value)

with open('/tmp/reactions.go', 'w') as f:
    f.write('package scheduler\n\n')
    f.write('var initialReactionPool = []*InitialReaction{\n')
    for go_ctor in go_ctors:
        f.write(go_ctor)
    f.write('}\n')
