import json
import random

SQL_FORMAT="\t({user_id}, {livestream_id}, '{word}', UNIX_TIMESTAMP()),\n"

with open('./initial-data/autogenerated_user_livestream_foreignkey_pairs.json', 'r') as f:
    fk_pairs = json.loads(f.read().rstrip())

with open('./initial-data/initial_ngwords.txt', 'r') as f:
    ngwords = list(line.rstrip() for line in f.readlines())

with open('/tmp/ngwords.sql', 'w') as f:
    f.write('INSERT INTO ng_words (user_id, livestream_id, word, created_at)\n')
    f.write('VALUES\n')
    for idx, ngword in enumerate(ngwords):
        user_id, livestream_id = random.choice(fk_pairs)
        sql = SQL_FORMAT.format(user_id=user_id, livestream_id=livestream_id, word=ngword)
        f.write(sql)
    user_id, livestream_id = random.choice(fk_pairs)
    f.write(f"\t({user_id}, {livestream_id}, '椅子パイプ', UNIX_TIMESTAMP());\n")
