import json
import random

SQL_FORMAT="\t({user_id}, {livestream_id}, '{word}', UNIX_TIMESTAMP()),\n"
GO_FORMAT="\t&InitialNgWord{{ UserID: {user_id}, LivestreamID: {livestream_id}, Word: \"{word}\" }},\n"

with open('./initial-data/autogenerated_user_livestream_foreignkey_pairs.json', 'r') as f:
    fk_pairs = json.loads(f.read().rstrip())

with open('./initial-data/initial_ngwords.txt', 'r') as f:
    ngwords = list(line.rstrip() for line in f.readlines())

sql_values = []
go_ctors = []
for idx, ngword in enumerate(ngwords):
    user_id, livestream_id = random.choice(fk_pairs)
    sql = SQL_FORMAT.format(user_id=user_id, livestream_id=livestream_id, word=ngword)
    sql_values.append(sql)
    go_ctor = GO_FORMAT.format(user_id=user_id, livestream_id=livestream_id, word=ngword)
    go_ctors.append(go_ctor)
user_id, livestream_id = random.choice(fk_pairs)
sql_values.append(f"\t({user_id}, {livestream_id}, '椅子パイプ', UNIX_TIMESTAMP());\n")
go_ctors.append("\t&InitialNgWord{{ UserID: {user_id}, LivestreamID: {livestream_id}, Word: \"椅子パイプ\" }},\n".format(user_id=user_id, livestream_id=livestream_id))

with open('/tmp/ngwords.sql', 'w') as f:
    f.write('INSERT INTO ng_words (user_id, livestream_id, word, created_at)\n')
    f.write('VALUES\n')
    for sql_value in sql_values:
        f.write(sql_value)

with open('/tmp/ngwords.go', 'w') as f:
    f.write('package scheduler\n\n')
    f.write('var initialNgWordPool = []*InitialNgWord{\n')
    for go_ctor in go_ctors:
        f.write(go_ctor)
    f.write('}\n')
