TRUNCATE FROM themes;
TRUNCATE FROM icons;
TRUNCATE FROM reservation_slots;
TRUNCATE FROM livestream_tags;
TRUNCATE FROM livestream_viewers_history;
TRUNCATE FROM livecomment_reports;
TRUNCATE FROM ng_words;
TRUNCATE FROM reactions;
TRUNCATE FROM tags;
TRUNCATE FROM livecomments;
TRUNCATE FROM livestreams;
TRUNCATE FROM users;

ALTER TABLE `themes` auto_increment = 1;
ALTER TABLE `icons` auto_increment = 1;
ALTER TABLE `reservation_slots` auto_increment = 1;
ALTER TABLE `livestream_tags` auto_increment = 1;
ALTER TABLE `livestream_viewers_history` auto_increment = 1;
ALTER TABLE `livecomment_reports` auto_increment = 1;
ALTER TABLE `ng_words` auto_increment = 1;
ALTER TABLE `reactions` auto_increment = 1;
ALTER TABLE `tags` auto_increment = 1;
ALTER TABLE `livecomments` auto_increment = 1;
ALTER TABLE `livestreams` auto_increment = 1;
ALTER TABLE `users` auto_increment = 1;