name: Bench Test
on:
  push:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/bench-test.yml
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.21.1
    name: Build
    runs-on: [isucon13-ci]
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    # containers
    - name: Setup containers(mysql,pdns,webapp)
      working-directory: ./development
      run: |
        make down/go
        make up/go

    # bench
    - name: "[bench] Get deps"
      working-directory: ./bench
      env:
        TZ: Asia/Tokyo
      run: |
        go get -v -t -d ./...

    - name: "[bench] Test"
      working-directory: ./bench
      env:
        TZ: Asia/Tokyo
      run: |
        go clean -testcache
        go test -p=1 -v ./...


