name: PHP CI
on:
  push:
    branches: [main]
    paths:
      - bench/**/*
      - webapp/php/**/*
      - webapp/sql/**/*
      - webapp/pdns/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-php.yml
      - development/Makefile
      - .github/workflows/php.yml
  pull_request:
    paths:
      - bench/**/*
      - webapp/php/**/*
      - webapp/sql/**/*
      - webapp/pdns/**/*
      - development/docker-compose-common.yml
      - development/docker-compose-php.yml
      - development/Makefile
      - .github/workflows/php.yml
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.21.1
    name: Build
    runs-on: [isucon13-ci-04]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup corepack
        run: corepack enable yarn

      # to avoid error: Deleting the contents of '/home/ubuntu/actions-runner/_work/isucon13/isucon13'
      #                 Error: File was unable to be removed Error: EACCES: permission denied, rmdir
      # https://github.com/actions/checkout/issues/211
      - name: chown workdir
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: "[frontend] build"
        working-directory: ./frontend
        run: |
          make

      # containers
      - name: "setup containers"
        working-directory: ./development
        run: |
          make down/php
          make up/php

      # bench
      - name: "[bench] Get deps"
        working-directory: ./bench
        env:
          TZ: Asia/Tokyo
        run: |
          go get -v -t -d ./...

      - name: "[bench] Test"
        working-directory: ./bench
        env:
          TZ: Asia/Tokyo
        run: |
          go clean -testcache
          go test -p=1 -v ./...

      - name: "run bench"
        working-directory: ./bench
        run: |
          make bench
